### ISSUE TITLE
AsciidoctorJ-Diagram not able to render PlantUML diagram

### ISSUE THREAD

**Issue by boerngen-schmidt** [asciidoctor/asciidoctor-intellij-plugin#817] opened 2021-07-29 09:53 UTC
The Asciidoc Plugin (version 0.33.6) is not able to render an example diagram from plantuml's homepage i.e. https://plantuml.com/object-diagram

I recieve the following IllegalStateException:
![2021-07-29 Asciidoc Plantuml ISE](https://user-images.githubusercontent.com/245062/127471009-8ae4a7c6-0045-49a2-b482-38575a734b7f.png)

The Plantuml Plugin for IntelliJ is able to render the diagrams without error. 

I tried uninstalled GraphViz 2.44.1. Updated to the latest version. -> No change
I tried upgrading Plantuml in the IntelliJPlugin to the latest version, but this did not have any effect, since it still says 1.2021.2 as plantuml version in the plugin.

**Comment by ahus1** [comment] 2021-07-29 16:11
Thanks for reporting this and sorry to hear this is giving you troubles.

To analyze this, please provide the following: 
* example AsciiDoc snippet with the PlantUML contents you used
* GraphViz version used

A all of the information below is available from the menu "Help | About | Copy" - please paste it as a comment in this issue: 
* operating system and version in use
* IDE name and version
* AsciiDoc plugin version
* list of other installed plugins together with their version

Thanks, Alexander

**Comment by boerngen-schmidt** [comment] 2021-07-29 19:36
As I said in the ticket:

- tried with Graphviz 2.44.1
- Graphiz latest
- currently no graphviz install, since asciidoc-diagram seems to have a version of dot bundled

```
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
You have a perpetual fallback license for this version.
Subscription is active until July 5, 2023.
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0 Verison 1607
GC: ParNew, ConcurrentMarkSweep
Memory: 1994M
Cores: 4
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: PlantUML integration (5.5.1), org.asciidoctor.intellij.asciidoc (0.33.6)
Kotlin: 212-1.5.10-release-IJ4746.92
```

Tried this snipplet. Variouis others also do not work
```
[plantuml]
----
@startuml
object London
object Washington
object Berlin
object NewYork

map CapitalCity {
 UK *-> London
 USA *--> Washington
 Germany *---> Berlin
}

NewYork --> CapitalCity::USA
@enduml
----
```

**Comment by boerngen-schmidt** [comment] 2021-07-29 19:38
Just out of curiosity could you tell me where the Pluigin hides the version of PlantUML used?

**Comment by ahus1** [comment] 2021-07-29 20:12
Thanks for providing the details. I gave it a try locally, and it worked for me. There seems to be a different in the setup, let's find it. 

The plugin forwards rendering of diagrams to asciidoctorj-diagram, that bundles asciidoctor-diagram and all dependencies, including PlantUML. The latest version of asciidoctor-diagram is 2.1.2, and this is also the version the latest version of the plugin uses. In order to have a more recent version of PlantUML in the plugin first asciidoctor-diagram needs to update and release. At the moment there is no way for a user to change these in the configuration of the plugin.

But as the diagrams work for me with the current version, this shouldn't be necessary to enable diagram rendering. Let's search for the difference that breaks it.

Please add the following snippet to your document to test your PlantUML/Graphviz setup; maybe it picks up a wrong Graphviz version somehow. 

```
[plantuml]
----
@startuml
testdot
@enduml
----
```

For me this renders:

![image](https://user-images.githubusercontent.com/3957921/127558757-db247ea4-45bd-4ee1-aa4f-ea9d0444fb9b.png)

What does it render on your PC?

Looking on my disk I found the on-demand extracted dot.exe here: `C:\Users\***\AppData\Local\Temp\_graphviz`.

Running `dot.exe -V` in that folder revealed: 

```
dot - graphviz version 2.44.1 (20200629.0846)
```

Do you have that folder as well? What does dot.exe render for you?

**Comment by boerngen-schmidt** [comment] 2021-07-30 10:27
It renders an Error
![2021-07-30 Testdot](https://user-images.githubusercontent.com/245062/127633629-9c6b9bb7-7d45-4edb-8c09-5297d67921ef.png)

I also found the on demand dot.exe in the same directory and the output is:
```
C:\Users\***\AppData\Local\Temp\_graphviz>dot -v
dot - graphviz version 2.44.1 (20200629.0846)
libdir = "C:\Users\***\AppData\Local\Temp\_graphviz"
Activated plugin library: gvplugin_dot_layout.dll
Using layout: dot:dot_layout
Activated plugin library: gvplugin_core.dll
Using render: dot:core
Using device: dot:dot:core
The plugin configuration file:
        C:\Users\***\AppData\Local\Temp\_graphviz\config6
                was successfully loaded.
    render      :  dot dot_json fig json json0 map mp pic ps svg tk vml xdot xdot_json
    layout      :  dot
    textlayout  :
    device      :  canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pic plain plain-ext ps ps2 svg tk vml xdot xdot1.2 xdot1.4 xdot_json
    loadimage   :  (lib) eps gif jpe jpeg jpg png ps svg

C:\Users\***\AppData\Local\Temp\_graphviz>dot -V
dot - graphviz version 2.44.1 (20200629.0846)
```

Funny tough the following simple diagram is rendered fine
```
[plantuml]
----
@startuml
A -> B
@enduml
----
```

The only thing I can guess what is happening here is, that some necessary part of Windows/Filesystem etc. is locked by our Domain settings. Also out Windows version is quite old (1607!!) 

Because of the error in SVG generation I did some tests. From https://renenyffenegger.ch/notes/tools/Graphviz/examples/index I got some examples and tested them with
```
C:\Users\***\AppData\Local\Temp\_graphviz>dot -v -Tsvg -O test.dot
dot - graphviz version 2.44.1 (20200629.0846)
libdir = "C:\Users\***\AppData\Local\Temp\_graphviz"
Activated plugin library: gvplugin_core.dll
Using render: svg:core
Using device: svg:svg:core
Activated plugin library: gvplugin_dot_layout.dll
Using layout: dot:dot_layout
The plugin configuration file:
        C:\Users\***\AppData\Local\Temp\_graphviz\config6
                was successfully loaded.
    render      :  dot dot_json fig json json0 map mp pic ps svg tk vml xdot xdot_json
    layout      :  dot
    textlayout  :
    device      :  canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pic plain plain-ext ps ps2 svg tk vml xdot xdot1.2 xdot1.4 xdot_json
    loadimage   :  (lib) eps gif jpe jpeg jpg png ps svg
pack info:
  mode   undefined
  size   0
  flags  0
  margin 8
pack info:
  mode   node
  size   0
  flags  0
fontname: "Arial" resolved to: [internal arial]
network simplex:  1 nodes 0 edges maxiter=2147483647 balance=1
network simplex: 1 nodes 0 edges 0 iter 0.00 sec
network simplex:  1 nodes 0 edges maxiter=2147483647 balance=1
network simplex: 1 nodes 0 edges 0 iter 0.00 sec
Maxrank = 0, minrank = 0
mincross: pass 0 iter 0 trying 0 cur_cross 0 best_cross 0
mincross: pass 0 iter 0 trying 0 cur_cross 0 best_cross 0
mincross D: 0 crossings, 0.01 secs.
network simplex:  2 nodes 1 edges maxiter=2147483647 balance=2
network simplex: 2 nodes 1 edges 0 iter 0.00 sec
routesplines: 0 edges, 0 boxes 0.00 sec
Using render: svg:core
Using device: svg:svg:core
gvRenderJobs D: 0.01 secs.

C:\Users\***\AppData\Local\Temp\_graphviz>
```
The SVG is fine and works!

Also running the following command works fine with java (java version "11.0.10" 2021-01-19 LTS) and (java version "1.8.0_241")
```
C:\Users\***\Downloads\plantuml>java -jar plantuml.1.2021.9.jar -testdot
Dot version: dot - graphviz version 2.44.1 (20200629.0846)
Installation seems OK. File generation OK
```

Next thing I tested was running PlantUML from the command line `java -jar plantuml.1.2021.9.jar -tsvg object.txt` with object.txt being the non working snipplet I provided to you and It works just fine!

Looking at the [code of PlantUML](https://github.com/plantuml/plantuml/blob/19822a5539da812b06171de0aa69b8b8639bacbe/src/net/sourceforge/plantuml/svek/DotStringFactory.java#L357) where  the exception originates seems like it can not find the width and height. PlantUML really should up their game with WHY an exception is thrown! And if I remember correctly I also once had an EmptySvgException, which is just a few lines above. Changing the output type with [plantuml, diagram-classes, png] does not change anything.

This leads me to believe the following:

- PlantUML to seems to work fine
- the bundled DOT seems to be fine
- Reading some issues seem to indicate some finagling with paths and plantuml
- High probability of running into some AD domain restrictions

**Comment by ahus1** [comment] 2021-07-30 10:52
Thanks for investigating all this. 

Could you please try to reproduce the issue with PlantUML 1.2021.2 (the version that it bundled in the plugin)? If that fails, upgrading the version in the plugin might help.

To be extra-sure: 
* Please download the Apache licensed PlantUML version (as this is the one that is bundled in the plugin).
* Clean the temporary _graphviz folder

Let's hope that the following reproduces the error:

```
java -jar plantuml.1.2021.2.jar -testdot
```

A different thought: does your home folder contain an umlaut? I've seen problems related to umlauts in other places before.

**Comment by boerngen-schmidt** [comment] 2021-07-30 11:48
So I downloaded the ASL 1.2021.2, cleaned _graphiz and the result
```
C:\Users\***\Downloads\plantuml-asl>java -jar plantuml-1.2021.2-asl.jar -testdot
Dot version: dot - graphviz version 2.44.1 (20200629.0846)
Installation seems OK. File generation OK
```

And no my userdir does not contain any Umlaut, but well spotted ;-)

**Comment by ahus1** [comment] 2021-08-04 14:37
I gave it some thoughts and also looked at the [PlantUML source code](https://github.com/plantuml/plantuml/blob/v1.2021.2/src/net/sourceforge/plantuml/cucadiagram/dot/GraphvizUtils.java#L284-L301).

Unfortunately it doesn't log additional information about the contents it receives. There is "OptionFlags.setCheckDotError()", but IMHO there is currently no way to do that. It could be helpful if Asciidoctor Diagram would allow a trace parameter to be passed down to PlantUML. Maybe you could raise this idea upstream.  

Looking at the code there are various ways to determine the location of the dot executable. There is also an option to pass on the dot executable via Asciidoctor Diagram. Maybe it would be good to remove all other dot.exe file from the local file system / from paths. 

You could try to reproduce the error when running Asciidoctor + Asciidoctor Diagram from the command line. Maybe that will narrow it down. 

I have to admit I'm running out of ideas here.

**Comment by ahus1** [comment] 2021-09-01 06:49
Sorry, closed the wrong issue. Re-opening ticket.

**Comment by mojavelinux** [comment] 2021-09-01 06:50
I'm not the right person to ping for asciidoctor-diagram. That would be pepijnve.

**Comment by ahus1** [comment] 2021-09-05 12:28
There is now pre-release 0.34.1 of this plugin available that includes an updated version of asciidoctor-diagram, that in turn includes PlantUML 1.2021.8. 

Please give that new version a try. 

That new version of PlantUML offers also an alternative to dot: "Smetana", see https://plantuml.com/en/graphviz-dot for the hint, and https://plantuml.com/en/smetana02 for more information. 

A diagram like the following should then render.

```
[plantuml]
----
@startuml
!pragma layout smetana
A -> B
@enduml
----
```

**Comment by ahus1** [comment] 2022-01-01 13:43
The information collected in this issue is now part of the docs: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/faq/could-not-find-dot-executable.html#symptom-could-not-run-dot-executable-for-plantuml

Closing issue. Will update docs further once more information becomes available.

**Closed by ahus1** 2022-01-01 13:43 UTC
Labels: bug
