### ISSUE TITLE
Preview panel stays on the screen after tab is closed

### ISSUE THREAD

**Issue by Forever-Young** [asciidoctor/asciidoctor-intellij-plugin#845] opened 2021-08-30 07:06 UTC
## Observed vs. expected behavior

Preview panel should be closed

## Steps to reproduce

1. Open any adoc file
2. Make sure preview panel is open
3. Close the tab
4. Preview panel is still there, over any other info, with "Initializing" message.

## Environment

Plugin Version: 0.33.18

IntelliJ Details: PyCharm 2021.2.1 (Professional Edition)
Build #PY-212.5080.64, built on August 25, 2021
Runtime version: 11.0.11+9-b1504.16 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: net.seesharpsoft.intellij.plugins.csv (2.17.1), com.paperetto.dash (3.3), com.intuit.intellij.makefile (1.0.15), String Manipulation (8.15.203.000.3), com.maxifom.pyenv-integration (0.0.2), org.intellij.plugins.hcl (0.7.10), Key Promoter X (2021.2), gr.jchrist.gitextender (0.7.0), com.mallowigi (38.0.0), zielu.gittoolbox (212.7.6), mobi.hsz.idea.gitignore (4.2.0), org.asciidoctor.intellij.asciidoc (0.33.18), com.chrisrm.idea.MaterialThemeUI (6.8.2), lermitage.intellij.extra.icons (1.60.0.203), ru.adelf.idea.dotenv (2021.3.0.212)

**Comment by ahus1** [comment] 2021-09-02 20:58
I'm sorry to hear this is a problem. I haven't yet managed to reproduce it (at least on Windows). 

Do you see a similar effect for the preview of Markdown files (it uses the same underlying technology, and I want to know if it is a more general problem).

Could you please send the log files of your IDE via E-Mail? You can find them via "Help | Show Log in Explorer". 
You find my email address in my GitHub profile. 

Thanks!

**Comment by Forever-Young** [comment] 2021-09-03 06:06
I sent you the logs.
After the recent update of the plugin, it shows white background panel (before it was grey with Initializing message).

As for Markdown files - no, it doesn't have the same problem.

**Comment by ahus1** [comment] 2021-09-04 10:45
I've analyzed the logs. I found some things that were strange, but that didn't point me to a problem. 

Things I found: 
* looking at the "threaddDump-freeze" elements, I found that the plugin "zielu.gittoolbox" appears quite often with a lot of threads, and handling StringBuffers. 
* sometimes the EDT (the one that is rendering the UI) was blocked for several seconds, maybe it was copying with lots of icons/UI elements?

I therefore ask you to temporarily disable all downloaded plugins except the AsciiDoc plugin, and then have a look if the problem persists. 

The recommended preview mode is JCEF. That's an acronym for a Chromium browser that is bundled with the IDE. To double-check: please go to the plugin's settings and look if "Preview browser" is set to "JCEF browser". 

The JCEF browser has a developer console like a regular browser. Once you enable [the "internal mode" of your IDE as described here](https://plugins.jetbrains.com/docs/intellij/enabling-internal.html), this developer console is available by right-clicking on the preview and selecting "Open DevTools".

Please have a look at the "Console" if this shows any errors. These errors might provide me with a clue how to proceed.

I'm also flagging this issue as "help wanted", as I have difficulties to reproduce it. It might be a MacOS thing, or something else.

**Comment by Forever-Young** [comment] 2021-09-06 11:43
I sent you more logs after disabling all plugins.
As for devtools, nothing is there. And nothing changes in that window after I close the adoc scratch. <- not sure if that's relevant, I have a problem with a scratch window after close.

**Comment by ahus1** [comment] 2021-09-07 06:24
Thank you for the additional log. Still no luck, I didn't see any warnings or exceptions. 

I tried with and without scratches, the preview doesn't stay open for me with PyCharm or IntelliJ.

Did you try a regular file, does it happen as well on regular files? Could you please try a new, empty scratch file if this behaves the same?

Thanks!

**Comment by Forever-Young** [comment] 2021-09-07 06:56
I'm not sure what happened, but now it doesn't stay on the screen.
Changing settings back and forth, setting Internal on, opening another adoc or whatever.
Before that, I recently reset the profile completely, and it was there after the reset, so I'm sure I had this problem :)

**Comment by Forever-Young** [comment] 2021-09-07 10:24
Nope. Still stays.
I came back after the break, opened the tab (scratch), with bottom pane (git) being opened. Closed the tab, preview (greyed) is on screen, over any tab, but only with height of that tab (minus bottom pane, whether it's there or not).
When I'm selecting "Initializing" in the preview pane, it's being selected, but also the text in the tab is being selected.
<img width="660" alt="image" src="https://user-images.githubusercontent.com/783188/132329327-9f007484-8ac8-4d95-86c8-90f99cfcee74.png">

**Comment by ahus1** [comment] 2021-09-08 08:16
Unfortunately I'm running out of ideas here. I assume this needs to be debugged on a mac. 

I asked if this this happens only for scratches, or also for regular AsciiDoc files. Did you give it a try?

A last set of ideas:
* what view mode do you use? Distraction free, zen, full screen, etc.?
* please create a thread dump via "Help | Diagnostic Tools | Dump Threads" - once the preview windows shows; maybe something is stuck.
* create a CPU profile, this might also show to me what happend in the threads. Start the CPU profiling before opening the scratch, and stopping once the preview is stuck. You start it via "Help | Diagnostic Tools | Start CPU Usage Profiling", and once you started it, you can stop it there as well. 

Please send the files to me via email. Thanks!

**Comment by Forever-Young** [comment] 2021-09-10 05:44
Sent you logs.

> what view mode do you use? Distraction free, zen, full screen, etc.?

any, tried normal, full screen.

> I asked if this this happens only for scratches, or also for regular AsciiDoc files. Did you give it a try?

Tried with regular, created new file, added a simple header, preview is rendered, I close the tab - I see a white pane.

Sometimes it's with "Initializing" and "transparent" to mouse events, sometimes it's white and apparently not "transparent" (nothing happens in the tab below it when I drag there).

**Comment by ahus1** [comment] 2021-09-10 21:19
As a workaround, I could suggest to switch to a JavaFX preview, I'm not sure how well this is supported on Mac; you'll need to install "JavaFX for plugins" first. See https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/javafx-preview.html for more details. 

Still, I want to get to the root of the problem.

I see that the API the Markdown plugin uses for the preview changed in 2021.2. Could you please try 2021.1 with the latest version of the AsciiDoc plugin plus JCEF preview and see how that works?

**Comment by ahus1** [comment] 2021-09-13 14:39
I installed on a Linux VM PyCharm 2021.2.1 plus the AsciiDoc plugin - this is as close as I can get to MacOS. Works without problems. Started to add plugins MaterialThemeUI, lermitage.intellij.extra.icons and zielu.gittoolbox - still not able to reproduce it.

**Comment by Forever-Young** [comment] 2021-09-13 14:46
From my part - 2021.1 works ok, JavaFX works too.

**Comment by ahus1** [comment] 2021-09-13 15:22
Note to self: Apparently there is an upstream issue here that has been closed https://youtrack.jetbrains.com/issue/JBR-3179
And a follow-up-issue, not closed yet: https://youtrack.jetbrains.com/issue/JBR-3661

I've published pre-release 0.34.2 that aligns the AsciiDoc and the Markdown plugin a little bit. Maybe you could give it a try. I'll published another alignment soon, unfortunately this will not be API compatible with 2021.1 any more :-(

**Comment by ahus1** [comment] 2021-09-13 16:29
The changes for #751 introduced "off screen rendering", maybe this solves also the overlapping problem in this issue. 

There is now pre-release 0.35.1 that requires 2021.2.1+

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Forever-Young** [comment] 2021-09-13 17:16
The pre-release version works fine.
Thank you very much :)

**Comment by ahus1** [comment] 2021-09-13 19:59
Finally! While JavaFX preview is a nice workaround, it doesn't offer all the features (and might soon be deprecated completely by JetBrains). 

I'll keep it as a pre-release for a week or two to see if there are negative effects in this change or other changes. I'll then promote it to a regular release.

I'll close this issue for now. Feel free to comment here once something doesn't work as expected with the preview, or open a new issue if it is unrelated.

**Comment by ahus1** [comment] 2021-09-13 19:59
Last but not least: thank you for your patience and repeated testing, it would not have worked without you!

**Closed by ahus1** 2021-09-13 19:59 UTC
Labels: bug, awaiting feedback, help wanted

**Comment by mamuf** [comment] 2021-09-17 14:39
I had the same issue and don't know if the plugin got updated (I don't think IJ updated in the meantime), but it started behaving correctly recently, so I just wanted to say it looks OK now. Thanks y'all for your effort.

**Comment by ahus1** [comment] 2021-09-17 14:45
Hi @mamuf - could you please state your IDE version and plugin version here? You find the information via "Help | About"; then press "Copy" and paste the clipboard's content here. It will contain the IDE version and the plugin version. Thanks!
