### ISSUE TITLE
Paragraph after image macro is handled as code in some cases

### ISSUE THREAD

**Issue by stdll** [asciidoctor/asciidoctor-intellij-plugin#1613] opened 2024-05-02 13:27 UTC
### Observed

Whenever I'm using the image macro and use more than one attribute (so I have to place a comma), the next paragraph gets a dark grey background and is handled like e.g. monospaced font. This means, among other issues, that xrefs aren't validated and the IDE doesn't check for grammar and spelling errors.

### Expected

The text after the image macro is handled as any other paragraph.

## Steps to reproduce

1. Create new AsciiDoc file in editor
2. Use the image macro and put more than one attribute within the brackets.
3. Write something in the next line(s).

### Markup sample

```
image::path/to/image.png[640,480]

Der nachfolgende Abschnitt wird wie Code dargestellt.
Egal wie viele Zeilen er hat.

Jetzt geht es wieder.
```

### Output sample

![bug-asciidoc-plugin](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/894220/651e9a98-ee8a-4bbe-a413-0380528152ab)

## Environment

Antora Version: 3.1.7
Asciidoctor: 2.2.6

Plugin Version: 0.41.13

IntelliJ Details: 
IntelliJ IDEA 2024.1.1 (Ultimate Edition)
Build #IU-241.15989.150, built on April 29, 2024
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (241.15989.113)
  com.intellij.plugins.xwinkeymap (211.4961.30)
  com.intellij.properties.bundle.editor (241.14494.150)
  org.asciidoctor.intellij.asciidoc (0.41.13)
  com.dmarcotte.handlebars (241.14494.150)
  org.sonarlint.idea (10.5.0.78339)
  mobi.hsz.idea.gitignore (4.5.3)
Kotlin: 241.15989.150-IJ

**Comment by ahus1** [comment] 2024-05-02 19:12
This seems to be a regression in plugin version 0.41.12. I'm sorry for breaking this and thank you for reporting it.

It will be fixed in the next version of this plugin. I'll comment on this issue once a pre-release is available.

**Closed** 2024-05-02 19:17 UTC
Labels: bug

**Comment by ahus1** [comment] 2024-05-03 07:22
Plugin-version 0.41.14 is now available with a fix. It should be available from the JetBrains markeplace soon. 

The it is also available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html).

**Comment by stdll** [comment] 2024-05-03 07:59
I can confirm that the fix is working. Thank you for fixing this issue this fast!
