### ISSUE TITLE
Antora plantuml diagrams rendering not working

### ISSUE THREAD

**Issue by austek** [asciidoctor/asciidoctor-intellij-plugin#1242] opened 2022-12-06 21:25 UTC
When using antora, plantuml diagrams are not rendering, however, are generated correctly on the generated site.

Here is a repo that reproduces the issue
https://github.com/austek/antora-diagram

Standard asciidoc file preview works `docs/asciidoc/index.adoc`

Open `docs/modules/ROOT/pages/index.adoc`, following error is shown
`Failed to generate image: undefined method `to_sym' for nil:NilClass (index.adoc, line 6) (script:process)`
## Environment
Plugin Version: 0.37.56

IntelliJ Details:
IntelliJ IDEA 2022.2.4 (Ultimate Edition)
Build #IU-222.4459.24, built on November 22, 2022
Runtime version: 17.0.5+7-b469.71 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 12
Metal Rendering is ON
Registry:
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.rust.lang (0.4.184.5057-222)
    name.kropp.intellij.makefile (222.4459.16)
    palantir-java-format (2.28.0)
    org.jetbrains.plugins.hocon (2022.1.0)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    com.intellij.guice (222.4459.16)
    com.euphoricity.gitignore (0.3)
    com.dmarcotte.handlebars (222.4459.16)
    com.intellij.lang.jsgraphql (3.3.0)
    String Manipulation (9.6.1)
    org.sonarlint.idea (7.2.1.58118)
    com.rspn.git (1.9)
    org.jetbrains.plugins.ruby (222.4459.16)
    org.asciidoctor.intellij.asciidoc (0.37.56)
    com.crunch42.openapi (1.41)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    CheckStyle-IDEA (5.74.0)
    spring-javaformat (0.0.34)
    ru.adelf.idea.dotenv (2022.2)
    com.haulmont.jpab (2022.5.0-222)
    com.zxy.idea.plugin.gradle-plugin-support (1.1)

Kotlin: 222-1.7.21-release-272-IJ4167.29

**Comment by ahus1** [comment] 2022-12-08 23:42
I'm sorry to hear this is not working for your diagrams. I can reproduce it locally when using Asciidoctor Diagram in IntelliJ. I can't offer a solution for this yet. In the meantime, I suggest that you enable Kroki in the plugin's settings, as this will generate the diagram as expected.

**Comment by Smasherr** [comment] 2024-01-10 11:17
I have a slightly different error message (MacOS, IntelliJ 2023.3.2, Asciidoctor-plugin 0.41.6), and I am also able to fix it by enabling Kroki.

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/10698205/ee8a4cee-7a90-471c-9eb6-e06bba122c18)

**Comment by ahus1** [comment] 2024-08-08 20:32
I'm closing this issue as the original references repository doesn't exist any more, so I can't reproduce it. 

@Smasherr - your issue looks different. Please open a bug report that includes also the diagram you want to render.

**Closed by ahus1** 2024-08-08 20:32 UTC
Labels: bug
