### ISSUE TITLE
Please update AsciidoctorJ Diagram to 2.2.8

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-intellij-plugin#1352] opened 2023-05-08 15:44 UTC
## Why the new feature should be added
AsciidoctorJ diagram has a bunch of fixes for d2 and jsyntrax in the 2.2.8 release.
https://github.com/asciidoctor/asciidoctorj-diagram/releases/tag/v2.2.8

## How the new feature should work

The bundled Version could be updated to 2.2.8. (Please :)

**Comment by ahus1** [comment] 2023-05-08 21:22
Thanks for raising this issue. It seems that it is not yet available on Maven central: https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj-pdf/

Let's look out when it appears there, and then this can be implemented.

**Comment by eiswind** [comment] 2023-05-09 15:35
Seems to be online now.
https://repo1.maven.org/maven2/org/asciidoctor/asciidoctorj-diagram/2.2.8/asciidoctorj-diagram-2.2.8.pom

Thanks for your great work. Don't know how to live without it.

**Comment by ahus1** [comment] 2023-05-15 21:34
There is now a pre-release 0.38.15 which includes the upgrade. I'd be happy if you could give it a try. Thanks!

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by eiswind** [comment] 2023-05-16 08:48
Diagram is ok, but I found that using syntax-highlighter=rouge is not working anymore

**Comment by ahus1** [comment] 2023-05-16 09:45
Could you please add an example code snippet and a screenshot?

**Comment by eiswind** [comment] 2023-05-16 13:07
Strange. In one Window it's failing:

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1238044/3f314786-0c55-4755-9e51-d3bfbf1560ac)

In the other one its fine:
![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1238044/27298dc8-5fce-4c3d-aa57-4cc6f676451f)

**Comment by eiswind** [comment] 2023-05-16 13:27
Came back to my IDE after 10 minute break, now everything is rendered fine in both windows. Very Strange.

**Comment by ahus1** [comment] 2023-05-16 20:48
Hm, strange, still good that it is reproducible on your side.

 Could you please provide more information on your environment? Go to the menu item "Help -> About".    Use the "Copy and Close" button and paste the information as a comment here. 

The message in the preview shows where to find the IDE's log file. I'd be happy if you could share it to me via email (my address is on my GitHub profile), or extract the exception / the Asciidoctor snippet out of it and paste it as a comment here.

**Comment by eiswind** [comment] 2023-05-17 06:42
```
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to Thomas Kratz
You have a perpetual fallback license for this version.
Subscription is active until July 7, 2025.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-41-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    org.rust.lang (0.4.194.5382-231)
    org.jetbrains.plugins.slim (231.8109.91)
    org.jetbrains.plugins.ruby (231.9011.34)
    org.asciidoctor.intellij.asciidoc (0.38.15)
    com.intellij.lang.jsgraphql (4.0.1)
    com.github.iguissouma.nxconsole (0.57.0)
    org.intellij.scala (2023.1.18)

Kotlin: 231-1.8.21-IJ9011.34
Current Desktop: ubuntu:GNOME
```

I'll send the log by email.

**Comment by ahus1** [comment] 2023-06-01 12:31
Thank you for the log and the version and plugins of your IDE. I suspect that there might be an incompatibility with the Ruby plugin (maybe also the Slim plugin). I still wasn't able to reproduce it. 

Could you give it a try and disable the Ruby plugin, and see if it still shows a the problem?

**Comment by eiswind** [comment] 2023-06-02 06:44
My guess would be the combination Scala+Ruby. I Uninstalled Scala Plugin, now everything is fine. Ruby Plugin still installed.

**Comment by ahus1** [comment] 2023-06-03 06:34
Thank for testing this. I'll close this for now as it works for me on a newer version of IDE, Scala and Ruby plugin.

**Closed by ahus1** 2023-06-03 06:34 UTC
Labels: enhancement, awaiting feedback
