### ISSUE TITLE
Asciidoc plug-in no longer accepting short-hand notations for include tags

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#744] opened 2021-05-04 09:42 UTC
## Observed vs. expected behavior

Parsing the include tag should accept:

`include::partial$node-installation.adoc[tags=!fullNode]`

as meaning the same as 

`include::partial$node-installation.adoc[tags=**;!fullNode]`

I'm sure it used to, but it doesn't any more.

The first form doesn't include anything from the file, when it should include everything except the tagged regions.

## Steps to reproduce

Create a file to include.
Set up some tags inside the file to include.
Try to exclude regions based on the tag.

## Environment

Plugin Version: 0.32.43

IntelliJ Details: ____

WebStorm 2021.1.1
Build #WS-211.7142.46, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins: com.intellij.properties (211.6693.44), com.jetbrains.plugins.code-notes-plugin (1.3), de.cmm.side_nodes (1.2), net.ntworld.nhat-phan.merge-request-integration-ce (2020.3.0-built-for-ide-2021.1.x), org.toml.lang (0.2.146.3826-211), com.intellij.lang.jsgraphql (2.9.1), org.asciidoctor.intellij.asciidoc (0.32.43), org.rust.lang (0.3.146.3826-211), com.github.shiraji.yaemoji (1.0.7)

**Comment by ahus1** [comment] 2021-05-04 16:58
Thanks for reporting this. This issue seems to be introduced by an update of Asciidoctor from version 2.0.12 to 2.0.14 in the AsciiDoc plugin for IntelliJ 0.32.42.

I used the CLI version of Asciidoctor to determine that the change happend between 2.0.12 and 2.0.13. I suspect the cause to be part of this commit https://github.com/asciidoctor/asciidoctor/commit/a1505efca095aa6a8ab33fb34a0937cd26cbe822

Reading the docs, the two should be equivalent as you pointed out: https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/

> !foo
> Equivalent to **;!foo; an exclusion without an inclusion implicitly starts by selecting all the lines that do not contain a tag directive.

I suggest the following: please create an issue in the [upstream Asciidoctor project](https://github.com/asciidoctor/asciidoctor/) for this.

**Comment by RayOffiah** [comment] 2021-05-04 17:30
Done!

https://github.com/asciidoctor/asciidoctor/issues/4048

**Comment by ahus1** [comment] 2021-05-05 08:11
Thanks for opening the issue. I see that this will be part of a future upcoming Asciidoctor and AsciidoctorJ release. 

This plugin will update to the lastest version of Asciidoctor as soon as it becomes available. I close this issue as there is nothing here to do for now. I hope you can cope with the workaround for the time being. Please comment if there is something else I can do, and I'll re-open the issue.

**Closed by ahus1** 2021-05-05 08:11 UTC
Labels: bug, upstream
