### ISSUE TITLE
rouge as source-highlighter

### ISSUE THREAD

**Issue by roganjoshua** [asciidoctor/asciidoctor-intellij-plugin#505] opened 2020-06-03 21:07 UTC
Waiting for the preview to render
trying to use rouge as the source highlighter

unable to render AsciiDoc document
org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /home/marty/development/documentation/learning/modules/Asciidoctor/pages/index.adoc: Failed to load AsciiDoc document - uninitialized constant Rouge::Lexers

org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /home/marty/development/documentation/learning/modules/Asciidoctor/pages/index.adoc: Failed to load AsciiDoc document - uninitialized constant Rouge::Lexers

(the full exception stack trace is available in the IDE's log file. Visit menu item 'Help | Show Log in Explorer' to see the log)

**Comment by ahus1** [comment] 2020-06-03 21:28
The current version of the plugin supports only coderay as source highlighter in the preview. 

Depending on your setup, you might be able to coderay highlighting in the plugin's preview, and rouge in the generated site.

Could you please provide a small source-code snippets that I can use to generate the error message you saw in your environment?

**Comment by roganjoshua** [comment] 2020-06-03 21:33
`source-highlighter: rouge`

I added the above to the asciidoc antora.yml file, removing it resolves the issue

**Comment by mojavelinux** [comment] 2020-06-03 21:34
@ahus1 This is caused by a problem in core. https://github.com/asciidoctor/asciidoctor/issues/3625

It can be fixed by upgrading rouge, but AsciidoctorJ hasn't done that yet to my knowledge.

**Comment by mojavelinux** [comment] 2020-06-03 21:35
If that is resolved, then rouge should work find in this environment. And rouge is now the preferred highlighter (along with highlight.js).

**Comment by ahus1** [comment] 2020-06-03 21:38
@roganjoshua - maybe you could try to add the "source-highlighter: rouge" to your playbook instead of the antory.yml file. I haven't tried it, but I'd be happy to hear if this helps in your setup. 
(the preview will only "see" attributes in the antora.yml, but not the attributes in the playbook)

**Comment by roganjoshua** [comment] 2020-06-03 21:41
Yeah I was considering that - there is an attribute precedence generally, I have really quite decided where I would like them right now. As Dan says, hopefully AsciidoctorJ will upgrade soon.

**Comment by mojavelinux** [comment] 2020-06-03 21:44
AsciidoctorJ will need to upgrade rouge to 3.19.0. See https://github.com/asciidoctor/asciidoctorj/blob/master/build.gradle#L62 I recommend filing an issue there.

**Comment by ahus1** [comment] 2020-06-13 10:31
Upstream issue tracked here: https://github.com/asciidoctor/asciidoctorj/issues/925

After this has been released, upgrade this plugin to the latest version of AsciidoctorJ, plus add necessary CSS to preview.

**Comment by ahus1** [comment] 2020-06-18 06:12
This will be part of the next release: supporting `rouge` as code syntax highlighter in preview. Documents can now override the code highlighter. Improved code syntax highlighting for preview in dark mode.

**Closed by ahus1** 2020-06-18 06:12 UTC
Labels: enhancement

**Comment by ahus1** [comment] 2020-06-18 16:24
There is now pre-release 0.30.80 that includes these changes. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
