### ISSUE TITLE
Typing in bigger Rider project very sluggish

### ISSUE THREAD

**Issue by enikao** [asciidoctor/asciidoctor-intellij-plugin#641] opened 2021-01-22 17:36 UTC
I'm using AsciiDoc in Rider. The project is quite large.
This used to work quite nicely with a previous version (before 2021), but now every keystroke takes 2 seconds.

It only happens if the preview pane is open.
It is not related to the renderer. Swing renderer shows same behavior, Markdown works without issues.

Looking into the Internal Tools process manager shows huge load on VFS.

I had a brief look in the code changes since then. Maybe the changes in `AsciiDoc.java` to use other ways of VFS access?

## Observed vs. expected behavior

Observed: Every keystroke in an `.adoc` file freezes the IDE for about 2 seconds.

Expected: Fluent typing.

## Steps to reproduce

1. Open a (maybe large?) VisualStudio `.sln` in  Rider
2. Open a `.adoc` file
3. Type something

## Environment

Rider for Unreal 2020.3.4
Plugin Version: 0.32.8 (same with 0.32.7)

IntelliJ Details:
Rider for Unreal Engine 2020.3.4
Build #RDCPPP-203.5981.165, built on January 15, 2021
Runtime version: 11.0.9.1+11-b1145.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Framework 4.0.30319.42000
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 5933M
Cores: 8
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, debugger.show.values.use.inlays=false, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, ide.tree.expand.navigatable.on.double.click.disabled=true, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false, ide.new.project.model=false
Non-Bundled Plugins: Abc.MoqComplete.Rider, com.microsoft.vso.idea, unreal-link, com.jetbrains.rider.android, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment] 2021-01-22 19:11
Thanks for reporting this, the behavior you see should definitely be fixed. 

There have been changes between 0.32.5 and 0.32.6 to support multiple project roots. Maybe this new code is too inefficient. 

Could you please try if the behavior disappears when switching to 0.32.5, and re-appear when switching to 0.32.6? 

You'll find all releases in the GitHub releases tab: https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases

Thanks in advance, Alexander

**Comment by enikao** [comment] 2021-01-23 10:26
You're correct, 0.32.5 works, 0.32.6 slugs.

**Comment by ahus1** [comment] 2021-01-23 18:12
Thanks for the fast feedback. I thought the additional operations would be in-memory only, apparently they are not or they are just not performant enough.

I prepared a pre-release 0.32.10 that includes both caching and makes background operations like rendering the preview interruptable. Please give it a try and let me know if this works for you.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by enikao** [comment] 2021-01-23 19:02
version 0.32.10 fixes the issue, thanks a lot!

**Comment by ahus1** [comment] 2021-01-23 19:30
That was a quick response! I'll test this new version in day-to-day work for the next few days before I promote it a regular release.

**Comment by enikao** [comment] 2021-01-25 12:47
I think you're invalidating caches a bit fast. I'm not sure yet if tabbing to another window or some VCS triggers invalidate the cache, but both happens frequently enough to make the .adoc file very hard to edit (as having it open freezes the IDE regularly).

**Comment by ahus1** [comment] 2021-01-25 23:12
There is a new pre-release 0.32.11 available. It will no longer invalidate the cache, instead it updates the cached value from the changed files. It's a bit more complex, but might help here to improve performance. 

Unfortunately I was still unable to reproduce the performance issue locally with large projects. 

If you still experience performance problems, please collect some CPU profiling information for me and send it to me via email. 

Following these steps to record profiling information (these are the menu items in IntelliJ, I hope they are the same for Rider: 

* Choose menu Help -> Diagnostic tools -> Start CPU Usage Profiling 
* work in you IDE for a minute or two 
* Choose menu Help -> Diagnostic tools -> Stop CPU Usage Profiling  
* Follow the notes in the event viewer to find the compressed profile file
* Send it to me via email. You find my email address in my GitHub profile. Please don't share it publicly as it will contain information about the project you've been working on in Rider

**Comment by enikao** [comment] 2021-01-26 10:08
In Rider, the project contents are managed (or at least closely synchronized) with the ReSharper engine, running in a different process. I guess that IPC introduces enough overhead to slow down VFS on large scale.

Admittedly, my project (solution in Rider lingo) is pretty large, at about 2300 Modules (Rider: projects).

**Comment by ahus1** [comment] 2021-01-27 07:18
There's another new pre-release 0.32.12. Given the number of 2300 modules I redesigned the data structure to handle that number more efficiently. 

Again, gathering some CPU profiling information would show the bottleneck. Is there an Open Source project with a similar number of modules that I could open in Rider?

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by enikao** [comment] 2021-01-27 12:25
Maybe you can try one of them? https://github.com/search?p=2&q=extension%3Asln+size%3A%3E2000000&type=Code
I'm actually using the preview version of Rider for Unity. Not to write games, but because it also supports C++ projects.

**Comment by ahus1** [comment] 2021-01-27 19:15
I chose one of the projects and gave it a try, but was unable to reproduce the issue with the old version of the plugin.

Therefore, please give the latest version 0.32.12 a test run. If the problem persists, please provide me with a CPU profiling file.

**Comment by ahus1** [comment] 2021-01-30 17:47
A new pre-release 0.32.14 is available with further performance improvements. 

If the UI is still lagging, instead of starting CPU profiling you can the the registry entry `performance.watcher.unresponsive.interval.ms` to have IntelliJ creating a thread dump every time the UI lags. 

The default is 5000 (5 seconds). You might need to lower this to maybe 1000, 500 or even 100. 

With this setting the IDE will record thread dumps every time the UI freezes for longer than the specified amount. Using "Help | Show Log in Explorer..." you'll find one folder per thread dump. These thread dumps shouldn't contain project information and are therefore easier to review and share. If you don't want to share them publicly, please send them to my email address listed in my GitHub profile.

**Comment by enikao** [comment] 2021-02-01 16:03
I'm currently more implementing than documenting. I'll get back to you once I use AsciiDoc again.

**Comment by ahus1** [comment] 2021-02-01 19:57
Thanks for letting me know. I'll keep the issue open for some more days to see if you encounter problems related to this issue. I'll then close it, but will re-open it once you comment on it again.

**Comment by enikao** [comment] 2021-02-12 12:57
I worked with version 0.32.17 for several days and didn't have any performance issues. Thanks for the fix!

**Comment by ahus1** [comment] 2021-02-12 20:57
Thank you for this feedback! I'll then close this issue.

**Closed by ahus1** 2021-02-12 20:57 UTC
Labels: awaiting feedback, bug
