### ISSUE TITLE
File names are partially duplicated when moving

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1117] opened 2022-07-28 13:32 UTC
## Observed vs. expected behavior

I've encountered an issue when file names in xrefs are becoming wrong after I move the current page and at least one other page to a subfolder.

Yes, it is a very specific error. I'm attaching a video to demonstrate what I mean.

## Steps to reproduce

[New Recording - 28.07.2022, 16:26:43](https://vimeo.com/734361970/0a4efa8a40)

You can try to reproduce the behavior by yourself if you use [this test repo.](https://github.com/Grolribasi/testrepo)

## Environment

IntelliJ IDEA 2022.2 (Community Edition)
Build #IC-222.3345.118, built on July 26, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.34)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by ahus1** [comment] 2022-07-28 18:31
Thanks for reporting this and taking the time for preparing the test case to reproduce it. I found that this happens when moving multiple files, where those files have internal references. It then tries to process the references twice, which breaks them. Will update the issue once a pre-release is available.

**Comment by Grolribasi** [comment] 2022-07-29 06:07
Thank you for the plugin and its support!

**Comment by ahus1** [comment] 2022-07-29 07:49
This change is now available as part of pre-release 0.37.35. I tested the change locally with the example your provided: As this works now as I expected it to work, I close this issue. If it doesn't work as you'd expect, please comment here and I'll re-open the issue.

I'll wait for some days for this and other changes to "burn in", and will then publish it as a regular release. If you'd like to have an earlier release due to, for example, the workflow in your team, please let me know. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment] 2022-08-01 13:41
Unfortunately, even after the update I still experience this error :(

**Comment by ahus1** [comment] 2022-08-01 17:27
I'm sorry to hear that it doesn't work for you yet. I reopen the issue.

I've tested again 0.37.36 (0.37.35 should work the same), and can't reproduce the problem any more.

Can you please confirm the version you've installed and that you restarted your IDE after installing the upgrade? Thanks!

**Comment by Grolribasi** [comment] 2022-08-02 06:51
I have version 0.37.35. The error occurs from time to time. But so far it seems like I haven't restarted IDE after the update.

**Comment by ahus1** [comment] 2022-08-02 08:04
Please restart the IDE after each plugin upgrade. While some plugin support an upgrade without a restart, the AsciiDoc plugin doesn't support it, yet. There should be a small notification after the download of the new release that asks for a restart.

Please let me know if it happens again a restart of the IDE.

**Comment by Grolribasi** [comment] 2022-08-02 12:59
I usually restart IDE. This time I forgot to.

So far, the error did not show itself again after the restart.

**Comment by Grolribasi** [comment] 2022-08-03 10:03
I caught the error again and was able to reproduce it. I have updated the test repository. You can try to batch move files starting with `task_GroupTask_` to `some-dir`.

**Comment by ahus1** [comment] 2022-08-03 18:20
Thank you for this additional test case. I reworked the logic to detect multiple moved files. This is part of pre-release 0.37.38.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment] 2022-08-04 06:12
I will try it out and report back. Thank you!

**Comment by Grolribasi** [comment] 2022-08-04 13:55
Working fine without any errors. I think, the issue can be closed.

**Comment by ahus1** [comment] 2022-08-04 18:28
Thanks for testing this again, and thanks for you patience. Closing this issue.

**Closed by ahus1** 2022-08-04 18:28 UTC
Labels: bug, awaiting feedback
