### ISSUE TITLE
Incorrect "AsciiDoc old style heading" warning

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#508] opened 2020-06-11 08:18 UTC
Consider the following example:

```
1. one
+
to
+
2. two
```

![invalid](https://user-images.githubusercontent.com/333276/84361905-ac436f00-abcc-11ea-8bc4-8963cec7058b.png)

If I replace `to` to `two` (no pun intended) then the issue is gone :thinking: 

**AsciiDoc Plugin Version**
`0.30.78`

**IDE Name and Version**

```
IntelliJ IDEA 2019.3.5 (Ultimate Edition)
Build #IU-193.7288.26, built on May 6, 2020
Licensed to Guillaume GROSSETIE
You have a perpetual fallback license for this version
Subscription is active until November 27, 2020
Runtime version: 11.0.6+8-b520.66 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-106-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: 
Non-Bundled Plugins: BashSupport, Batch Scripts Support, CMD Support, CheckStyle-IDEA, FindBugs-IDEA, JFormDesigner, com.dmarcotte.handlebars, com.intellij.ideolog, com.jetbrains.lang.ejs, com.jetbrains.plugins.jade, com.wix.eslint, org.asciidoctor.intellij.asciidoc, org.intellij.scala, org.jetbrains.idea.grammar, org.jetbrains.kotlin, org.jetbrains.plugins.slim, org.jetbrains.plugins.ruby
```

**Comment by mojavelinux** [comment] 2020-06-11 08:28
An setext style heading all by itself would be valid with only a single plus. Obviously, not in this context though. I'm willing to guess, however, that it's extremely rare that an setext style heading would ever be a single character. So a quick way to fix this would be to increase the length of the check to two characters.

...however, if you can fix it by comprehending the context in which it occurs, that would be even better.

**Comment by ahus1** [comment] 2020-06-11 10:19
@Mogztter - thanks for reporting this. 

The setext style heading implementation of Asciidoctor allows the second line to be exactly the length of the heading or one character more or less than the heading. This describes the effect you see when changing it from "to" (one character longer than the single plus in the second line) to "two" (two characters longer than the second line). 

The current lexer has a "test driven" approach (some might say "corner case" or "bug driven" approach), so every report makes it better. Minimal examples like you have provided help a lot.

I'll have a look into the lexer and will get back probably with a pre-release.

**Comment by ahus1** [comment] 2020-06-11 10:21
@mojavelinux - I'll have a look and will strive for a proper solution (as usual). I look forward for the AsciiDoc WG to name the different contexts.

**Comment by ahus1** [comment] 2020-06-11 12:06
There is now a pre-release 0.30.79 that fixes this issue. Please give it a try.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment] 2020-06-24 20:46
I assume this works now and close this issue. If you experience problems, please comment and I'll re-open this issue.

**Comment by Mogztter** [comment] 2020-06-25 06:30
@ahus1 I'm using 0.30.80 and I can still see the warning:


![plugin](https://user-images.githubusercontent.com/333276/85667702-2c360280-b6be-11ea-937f-3d2fec43a4b6.png)

![old-style-heading](https://user-images.githubusercontent.com/333276/85667705-2cce9900-b6be-11ea-8dac-1b96800ad9b3.png)

**Comment by ahus1** [comment] 2020-06-25 06:59
Thanks for providing this additional example. The plugin wouldn't warn if you add line with a single "+". I re-opened the issue and will look into the lexing/parsing.

doesn't work yet:

```
1. xxxx
+
[source]
----
Hi
----
to
+
----
Hi
----
```

works:

```
1. xxxx
+
[source]
----
Hi
----
+
to
+
----
Hi
----
```

**Comment by ahus1** [comment] 2020-06-28 10:15
There is now release 0.31.8 (for IntelliJ 2020.2 EAP) and pre-release 0.30.82 (for releases before IntelliJ 2020.1 and before) that should fix this. 

It contains several refactorings and new test cases to handle contexts in lists better than before. There should be less false positive recognized enumerations due to this. 

If you see regressions in the editor highlighting and/or re-formatting, please let me know and I'll re-open this issue.

**Closed by ahus1** 2020-06-28 10:15 UTC
Labels: bug
