### ISSUE TITLE
Preview of adoc is not available in  detached window  mode

### ISSUE THREAD

**Issue by jvmlet** [asciidoctor/asciidoctor-intellij-plugin#1258] opened 2022-12-18 09:43 UTC
## Observed vs. expected behavior

Preview of `adoc` file is not available in  detached window  mode

## Steps to reproduce

Rider  `2022.3` introduced detached window mode where specific tab can be detached to it's own window.
 Right click on tab ->`Move tab to new window`

## Environment

Plugin Version:  0.38.4

 ````
JetBrains Rider 2022.3
Build #RD-223.7571.232, built on December 5, 2022
Licensed to XXXX

Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4024M
Cores: 8
Registry:
    ide.workspace.model.rbs.as.tree=false
    ide.new.project.model.index.case.sensitivity=true
    indexing.enable.entity.provider.based.indexing=false
    vcs.empty.toolwindow.show=false
    platform.projectModel.workspace.model.file.index=false
    database.show.search.tab=false
    rdclient.asyncActions=false

Non-Bundled Plugins:
    Batch Scripts Support (1.0.13)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    org.intellij.plugins.hcl (223.7571.175)
    PlantUML integration (5.20)
    com.intellij.lang.liquid (223.7571.203)
    com.intellij.plugin.adernov.powershell (2.0.10)
    org.asciidoctor.intellij.asciidoc (0.38.4)
    com.intellij.rider.plugins.nuke (2022.3.0)
    ru.adelf.idea.dotenv (2022.3)
    org.sonarlint.idea (7.2.1.58118)
    com.microsoft.vso.idea (1.162.1)
    com.intellij.resharper.azure (3.50.0.1519-2022.3)
````

**Comment by ahus1** [comment] 2022-12-18 17:16
Thanks for reporting this, and sorry to hear this is causing you problems. 

I was able reproduce this in IntelliJ as well. While I work on a solution, here's a workaround that worked for me in IntelliJ: Briefly hide and preview, then show it again using the icons on the toolbar. Then the preview initializes. 

![image](https://user-images.githubusercontent.com/3957921/208310750-d6bdf85b-a698-4ff7-a328-3544791ce024.png)

**Comment by jvmlet** [comment] 2022-12-18 20:12
@ahus1, thanks for addressing this. No need to feel sorry, open source is about collaboration, just wanted to contribute, at least by opening the issue.
Great plugin BTW, thanks a lot.
You are more than welcome to check out mine (if you use gradle) .

**Comment by ahus1** [comment] 2022-12-19 08:37
There's now a fix available which is part of pre-release 0.38.5. Testing it locally in IntelliJ, it resolved the problem for me. I also solved a situation where the preview kept showing "Initializing..." until the user did the first change in the doc. 

Please let me know if this version works for you as well.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment] 2022-12-27 12:49
I didn't hear back from you yet. Still, as it now works for me, I close this issue. If the issue remains, please comment here and I'll re-open the issue.

**Closed by ahus1** 2022-12-27 12:49 UTC
Labels: bug, awaiting feedback

**Comment by jvmlet** [comment] 2022-12-27 13:29
thanks @ahus1
