### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by victorherraiz-santander** [asciidoctor/asciidoctor-intellij-plugin#1217] opened 2022-11-15 21:56 UTC
## Observed vs. expected behavior

High CPU usage with no document opened.

```
 %CPU  Subsystem

249.0  <Process total CPU usage>
 73.5  Plugin AsciiDoc: org.asciidoc.intellij.psi
 64.8  psi.search (in com.intellij)
 35.2  <JIT compiler>
 13.9  vfs.newvfs.impl (in com.intellij.openapi)
  6.3  vfs (in com.intellij.openapi)
  4.9  <Activity Monitor>
  4.7  <infrastructure: AWT-AppKit>
```

These happens quite often when I edit normal java files across the project.

## Steps to reproduce

Just working with java files

## Environment

Plugin Version: 0.37.54

```
IntelliJ Details: 
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
    some.awesome (1.14)
    com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
    org.jetbrains.plugins.spotbugs (1.2.5)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    com.jetbrains.jax.ws (222.4345.14)
    net.seesharpsoft.intellij.plugins.csv (3.0.1-222)
    org.sonarlint.idea (7.2.0.56810)
    org.asciidoctor.intellij.asciidoc (0.37.54)
    CheckStyle-IDEA (5.73.0)
    org.intellij.scala (2022.2.17)
Kotlin: 222-1.7.21-release-272-IJ4167.29
```

**Comment by victorherraiz-santander** [comment] 2022-11-15 22:02
Another snapshot from activity monitor:
```
315.1  <Process total CPU usage>
 86.1  Plugin AsciiDoc: org.asciidoc.intellij.psi
 71.3  psi.search (in com.intellij)
 44.6  <JIT compiler>
 15.9  vfs.newvfs.impl (in com.intellij.openapi)
 11.8  vfs (in com.intellij.openapi)
  6.8  progress (in com.intellij.openapi)
  5.3  <Activity Monitor>
```
No open adoc files

**Comment by ahus1** [comment] 2022-11-15 22:21
Thanks for reporting this. To analyze this, I need some profiling information.

Choose "Help | Diagnostic Tools | Start CPU Usage Profiling" and let it profile the CPU usage for approx. one minute. Then stop it, and send the file to me via email to the email address listed in my GitHub profile. I'll then analyze it.

**Comment by ahus1** [comment] 2022-11-25 08:12
Closing this as a duplicate of #1226 as no reply with additional information was sent to me. If you have more information on this issue, please add a comment and I'll re-open this issue.

**Closed by ahus1** 2022-11-25 08:12 UTC
Labels: bug, awaiting feedback
