### ISSUE TITLE
Case-sensitivity for images

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#863] opened 2021-09-15 13:18 UTC
## Observed vs. expected behavior

Antora is case-sensitive when it comes to images: `TheImage.png` is not the same as `theImage.png`. If the capitalization of an image is wrong in the path, the image will not be displayed on the website page.

However, IntelliJ plugin ignores capitalization. The plugin recognizes `TheImage.png` and `theImage.png` as the same thing and displays the image in the preview without issues.

Expected behavior: the plugin warns about wrong path capitalization.

## Steps to reproduce

Create an Antora project, add images, refer to an image with the wrong path capitalization, build a website with Antora.

## Environment

Plugin Version: 0.33.19

IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2044M
Cores: 8
Non-Bundled Plugins: org.asciidoctor.intellij.asciidoc (0.33.19), com.github.jk1.ytplugin (1.2.9)
Kotlin: 212-1.5.30-release-409-IJ4638.7

As discussed in Antora [chat](https://antora.zulipchat.com/#narrow/stream/282400-users/topic/IntelliJ.20plugin.20and.20case-sensitivity) the issue seems to be caused by different environments for authoring and website building. If the source AsciiDoc is authored using IntelliJ in Windows, it doesn't check if the capitalization in the path is correct, but a website built with Antora under Linux is always case-sensitive.

**Comment by ahus1** [comment] 2021-09-16 08:31
Thanks for raising this, this will be helpful to a lot of users. 

I re-labeled it as an enhancement as this is as I understand it not a bug that breaks an existing feature, but a new, missing feature to add an inspection like that.

**Comment by Grolribasi** [comment] 2021-09-17 07:48
Yes, thanks for re-labeling. I had doubts as to which category it would belong to.

**Comment by ahus1** [comment] 2021-09-17 15:41
There is now pre-release 0.35.3 that includes a change for this. I tested it locally and and it worked for some local examples I prepared. Please give it a try and comment here if it works for you as well.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html) - it might take a little time until it is available in the EAP repository.

**Comment by Grolribasi** [comment] 2021-09-20 09:22
This is working on my examples too so it should work as expected on other examples.

**Comment by ahus1** [comment] 2021-09-20 19:39
Thank you for the feedback, I'll then close this issue. I plan to promote this to regular release some time next week.

**Closed by ahus1** 2021-09-20 19:39 UTC
Labels: enhancement, awaiting feedback
