### ISSUE TITLE
Auto-formatting corrupts content when front-matter keys contain dashes

### ISSUE THREAD

**Issue by feliksik** [asciidoctor/asciidoctor-intellij-plugin#1606] opened 2024-04-23 11:45 UTC
## Observed vs. expected behavior

A dash in the frontmatter keys causes the  autoformatter to corrupt the file. Seems that it's triggered by the same grammar bug as #1595 . 

## Steps to reproduce

```
---
a-c: b
---
= The title

The dash in the `a-c` key causes the auto-formatter to corrupt the file. 
```

It is formatted as follows: 

```
---

a-c: b --- = The title

The dash in the `a-c` key causes the auto-formatter to corrupt the file. 
```

## Environment

Plugin Version: 0.41.13

IntelliJ Details: IntelliJ IDEA 2023.3.5 (Ultimate Edition) Build #IU-233.14808.21, built on March 12, 2024

**Comment by ahus1** [comment] 2024-05-02 21:40
Yes, this is a duplicate of #1595

**Closed by ahus1** 2024-05-02 21:40 UTC
Labels: bug
