### ISSUE TITLE
Doesn't work on PHPStorm 2018.1.6

### ISSUE THREAD

**Issue by wolfheart** [asciidoctor/asciidoctor-intellij-plugin#214] opened 2018-08-28 09:55 UTC
```Event log: Error rendering asciidoctor: Error rendering asciidoctor: org.jruby.exceptions.RaiseException: (Errno::ENOENT) file:/C:/Users/account/.PhpStorm2018.1/config/plugins/asciidoctor/lib/asciidoctorj-1.5.6.jar!/specifications/open-uri-cached-0.0.5.gemspec```

Using just a simple document:
```
= Testdoc
Some test...
```

AsciiDoc Plugin Version: 0.20.6

IDE Name and Version: PhpStorm 2018.1.6
Build #PS-181.5281.35, built on June 14, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ahus1** [comment] 2018-08-29 22:07
Hello @wolfheart, thanks for reporting this issue. Unfortunately I can't reproduce the issue on my system. 

The ENOENT indicates that it can't find the file specified above ... but it is definitely packaged within the distributed asciidoctorj-1.5.6.jar. Could you please check the contents of the file (using an unzip tool of your choice like i.e. 7ZIP) that your JAR file is not corrupt and that it contains a file specifications/open-uri-cached-0.0.5.gemspec?

**Comment by wolfheart** [comment] 2018-08-30 06:53
Yes, the `asciidoctor-1.5.6.jar` seems to be sane and contains `specifications/open-uri-cached-0.0.5.gemspec`. But I still get the error above. Do I miss some other plugins, which have to be installed prior?

```
# -*- encoding: utf-8 -*-
# stub: open-uri-cached 0.0.5 ruby lib

Gem::Specification.new do |s|
  s.name = "open-uri-cached"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Danial Pearce"]
  s.date = "2012-01-07"
  s.description = "OpenURI with transparent disk caching"
  s.email = "rubygems@tigris.id.au"
  s.homepage = "http://github.com/tigris/open-uri-cached"
  s.rubygems_version = "2.4.8"
  s.summary = "Do a lot of site scraping but take lots of attempts at parsing the content before reaching your end result? This gem is for you. But wait, there's more... Ok, no there isn't."

  s.installed_by_version = "2.4.8" if s.respond_to? :installed_by_version
end
```

**Comment by ahus1** [comment] 2018-08-30 09:42
The Asciidoctor Plugin doesn't depend on other plugins. But I could conflict with other plugins (although I can't recall a situation when this actually happened). 

Looking at the error message there could be a conflict on JRuby that this plugin includes. Another plugin might have a conflicting version. 

There are multiple ways to analyze this that I can think of: 

* Have a look into your `.PhpStorm2018.1/config/plugins/` folder. Look for a file called jruby*.* in any of the plugin folders or in the plugin JARs. If uninstalling/disabling the plugin helps, we then know how to reproduce the problem
* Post a list of the plugins you have installed. Listing the directories and JAR files in the plugins folder should give the list (there might be other ways). That would leave figuring out the problematic plugin to me (and my spare time).
* Trial and error: remove (or disable) plugins until the Asciidoctor plugin works

**Comment by wolfheart** [comment] 2018-08-31 07:48
I moved to PHPStorm 2018.2.2 and deactivated all plugins, which have been installed manually (in `.PhpStorm2018.1/config/plugins/`) but still experience that error.

The list of installed plugins is
- asciidoctor - of course ;)
- GrepConsole (inactive)
- Presentation Assistent (inactive)
- IDEA-Native-Terminal-Plugin (inactive)
- PHPInspectionsEA (inactive)
- php-toolbox (inactive)

**Comment by ahus1** [comment] 2018-09-06 19:05
There is a similar bug #210 - just to double check the log message you've given above: 

Did you replace your real user name with "account"? Does your user name / full path to your home directory contain an Umlaut?

**Comment by wolfheart** [comment] 2018-09-10 07:40
Yes, you're right: `file:/.../Users/Michael MokroÃŸ/.PhpStorm2018.2/config/...` There is both an Umlaut and whitespace.

**Comment by ahus1** [comment] 2018-09-11 16:01
Ok, I then close this bug as a duplicate. Please follow #210 for information.

**Closed by ahus1** 2018-09-11 16:01 UTC
