### ISSUE TITLE
graphviz not working

### ISSUE THREAD

**Issue by Hanterdro** [asciidoctor/asciidoctor-intellij-plugin#191] opened 2017-09-18 15:07 UTC
Intellij 2017.2.4

```
[graphviz]
----
 digraph Beziehungen {
   nodesep=0.7
   Jutta -> Franz [label="liebt"]
   Bernd -> Franz [label="hasst"]
   Franz -> Bernd [label="hasst"]
   Franz -> Jutta [label="liebt"]
   Bernd -> Jutta [label="liebt"]
   Mark -> Franz [label="bevorzugt4"]
}
----
```

leads to 

```
Failed to generate image: Could not find the 'dot' executable in PATH; add it to the PATH or specify its location using the 'graphvizdot' document attribute
 digraph Beziehungen {
   nodesep=0.7
   Jutta -> Franz [label="liebt"]
   Bernd -> Franz [label="hasst"]
   Franz -> Bernd [label="hasst"]
   Franz -> Jutta [label="liebt"]
   Bernd -> Jutta [label="liebt"]
   Mark -> Franz [label="bevorzugt4"]
}
```

graphviz is installed through brew `brew install graphviz`
```
which dot
/usr/local/bin/dot

echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by ahus1** [comment] 2017-09-18 19:09
I'm no mac user. Any other mac user using graphiz?

Did you try to execute "dot -h" on the command line to find out if the file is executable?

Did you start IntelliJ from that shell to ensure that the path is really set for the IntelliJ process (just guessing here... maybe the path wasn't set when you started IntelliJ)?

**Comment by mojavelinux** [comment] 2017-09-18 19:12
> Did you start IntelliJ from that shell to ensure that the path is really set for the IntelliJ process (just guessing here... maybe the path wasn't set when you started IntelliJ)?

That's my guess. I bet the shell session running IntelliJ is the desktop environment shell and it is usually vastly different from the shell session you get when running a terminal.

**Comment by ahus1** [comment] 2017-10-02 17:06
@Hanterdro - did the tips from Dan and me help? Or did you find another solution? 

Please comment.

**Comment by Hanterdro** [comment] 2017-10-02 17:08
Sorry, I have currently a lot of work. I hope I find this week time to check your ideas. Sounds at least reasonable :)

**Comment by ahus1** [comment] 2017-10-28 15:25
I close this bug for now. Please re-open if this problem persists.

**Closed by ahus1** 2017-10-28 15:25 UTC
Labels: help wanted

**Comment by qiyuqi** [comment] 2018-01-15 06:19
the problem is still exist. 
i have tried with mac and win environment, the preview present message as follow:
> Failed to generate image: Could not find the 'dot' executable in PATH; add it to the PATH or specify its location using the 'graphvizdot' document attribute

**Comment by tntclaus** [comment] 2018-02-17 03:50
@qiyuqi it is not the plugin problem, but the problem of Mac OS, that limits `$PATH` for all GUI apps to `/usr/bin:/bin:/usr/sbin:/sbin`. 

Here is the list of solutions:
http://depressiverobot.com/2016/02/05/intellij-path.html

**Comment by wfouche** [comment] 2019-05-24 01:31
The solution to this problem is for **IntelliJ/Asciidoc** to detect environment variable ```GRAPHVIZ_DOT``` when processing Graphviz diagrams.

On Windows, for example, I've set this variable to the location of the dot.exe file:

```GRAPHVIZ_DOT=C:\WS\Apps\graphviz-2.38\release\bin\dot.exe```

See page http://plantuml.com/graphviz-dot for a discussion of GRAPHVIZ_DOT.

The Plantuml content below renders correctly in IntelliJ/Asciidoc.

```
[plantuml, uml-example, png]
----
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
----
```

However, the Graphviz content

```
[graphviz, dot-example, svg]
----
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
----
```

generates the message:

```
Failed to generate image: Could not find the 'dot' executable in PATH; add it to the PATH or specify its location using the 'graphvizdot' document attribute
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
```

Please locate the dot program using environment variable GRAPHVIZ_DOT (if defined) when processing Graphviz content.

**Comment by ahus1** [comment] 2019-05-30 20:13
Working on feature #261 I found I found the following possibility that exists since version the pugin's version 0.21.1 

Please configure the attribute _graphvizdot_ in the plugin's settings like shown in the screenshot below. 

![graphviz-config](https://user-images.githubusercontent.com/3957921/58661177-816edb80-8327-11e9-9a3e-81ac8cadfbb4.png)

This should work independent of the operating system.

Future versions of the plugin might have a more intuitive and convenient way to configure this. Issue #261 will track further development.
