### ISSUE TITLE
Code completion closes by itself and becomes unusable

### ISSUE THREAD

**Issue by stangls** [asciidoctor/asciidoctor-intellij-plugin#206] opened 2018-04-16 16:04 UTC
AsciiDoc Plugin Version: 0.20.0
IDE Name and Version: IntelliJ Ultimate 2018.1.1 IU-181.4445.78

Problem: Code completion closes by itself and becomes unusable.

See also: https://youtrack.jetbrains.com/issue/IDEA-190330

**Comment by tobiashochguertel** [comment] 2018-04-30 08:43
I have similar troubles. IntelliJ IDEA stops working, when I select an Asciidoc file in project tree.
When I uninstall the asciidoc plugin, then IDEA works like expected.

**Asciidoc Plugin Version: 0.20.2**

**IntelliJ IDEA Ultimate 2018.1**

> Build IU-181.4203.550, built on March 26,2018
> JRE: 1.8.0_152-release-1136-b20 x86_64
> JVM: OpenJDK 64-Bit Server VW by JetBrains s.r.o

_Logs form Intellij:_

- [idea.log](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/1959899/idea.log)
- [threadDumps-freeze-20180430-103529-IU-181.4203.550.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/1959925/threadDumps-freeze-20180430-103529-IU-181.4203.550.zip)

**Comment by ahus1** [comment] 2018-05-06 19:51
@tobiashochguertel your issue doesn't seem to be related. I move this to #207

**Comment by ahus1** [comment] 2018-05-06 19:58
@stangls - code completion works for me within Java projects. 

Please provide for me a minimal (Kotlin?) project that allows me to reproduce the issue. 

Thanks!

**Comment by stangls** [comment] 2018-05-24 14:57
I am currently not upgrading IntelliJ due to other bugs in the software.
It is highly possible, that the newest IDEA will not have these kind of problems anymore.
If not, I will come back as soon as possible with an example code.

**Comment by ahus1** [comment] 2018-05-24 16:39
Thanks for the comment - I will close the issue for now.

**Closed by ahus1** 2018-05-24 16:39 UTC
Labels: awaiting feedback
