### ISSUE TITLE
Sync code&preview doesn't work for the second paragraph of a NOTE

### ISSUE THREAD

**Issue by ge0ffrey** [asciidoctor/asciidoctor-intellij-plugin#160] opened 2016-11-30 14:36 UTC
Deep down in an adoc file, I have this text:

```
Every `<solverBenchmark>` element contains a solver configuration and one or more `<inputSolutionFile>` elements.
It will run the solver configuration on each of those unsolved solution files.
The element `name` is optional, because it is generated if absent.
The `inputSolutionFile` is read by a <<solutionFileIO,SolutionFileIO>> (relative to the working directory).

[NOTE]
====
Use a forward slash (``/``) as the file separator (for example in the element ``<inputSolutionFile>``). That will work on any platform (including Windows).

Do not use backslash (``\``) as the file separator: that breaks portability because it does not work on Linux and Mac.
====
```

When I click on the line "Do not use backslash ..." the preview page jumps to the beginning of the file, instead of to that line.

**Comment by ahus1** [comment] 2016-12-02 16:01
Thank you for the accurate description and the example. 

I was able to find the cause. A fixed version 0.17.1 is available form the [Github Releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) as a preview release.

The 0.17.x branch includes a refurbished parser for syntax highlighting in the editor (#143). Due to this the 0.17.x  is only available as a preview until it proves to be stable in my day-to-day work. I'd be happy if you would give it a try as well.

I'm closing this ticket as I have tested this issue successfully using your example. I you still experience this issue, please re-open this ticket.

**Closed by ahus1** 2016-12-02 16:01 UTC
