### ISSUE TITLE
Relative include no longer working since 0.38.6

### ISSUE THREAD

**Issue by mmoerdijk** [asciidoctor/asciidoctor-intellij-plugin#1298] opened 2023-02-17 15:08 UTC
## Observed vs. expected behavior

When including a file from the same directory the included file is not found.

## Steps to reproduce

1. Make a adoc file that includes a another file in the same directory like the one below
file.adoc
```adoc
include::otherfile.adoc[]
```
2. Open the file in pycharm and look a the preview.
3. Since 0.38.6 this doesn't longer work.

When the path is changed to:
```adoc
include::./otherfile.adoc[]
```
It is loaded correctly.

## Environment

Plugin Version: 0.38.6-10
OS: Linux
Editor: PyCharm 2022.3.2 (Professional Edition)

IntelliJ Details: PyCharm 2022.3.2 (Professional Edition)
Build #PY-223.8617.48, built on January 24, 2023
Licensed to Mart Moerdijk
Subscription is active until May 22, 2023.
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.0.12-76060006-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    debugger.watches.in.variables=false
    python.use.targets.api=false

Non-Bundled Plugins:
    edu.umontreal.hatchery (0.2.1)
    org.rust.lang (0.4.188.5205-223)
    PlantUML integration (5.22.0)
    org.asciidoctor.intellij.asciidoc (0.38.5)
    com.leinardi.pycharm.mypy (0.14.0)
    zielu.gittoolbox (500.0.3+213)

Current Desktop: pop:GNOME

**Comment by ahus1** [comment] 2023-02-17 17:53
Hi @mmoerdijk - sorry to hear this is causing you troubles, and thanks for reporting this here. 

I tried to reproduce this with plugin version 0.38.10, and it was working for me:

![image](https://user-images.githubusercontent.com/3957921/219736949-50814114-8e31-44d2-ba46-6182dd9ea360.png)

![image](https://user-images.githubusercontent.com/3957921/219737118-bcd95547-3d7b-4b78-898e-e4e0787c35dc.png)


Could you please add a screenshot of your editor and preview, and the file structure of your example project? If you could point to an example on GitHub, this would be helpful as well. 

Thanks!

**Comment by mmoerdijk** [comment] 2023-02-17 20:42
Hi @ahus1 

Sorry, for the incomplete bug report, I was to0 much in a hurry.

The issue is more complex than I thought.

Turns out it only happens if there is `antora.yaml` in the directory tree and it files are in a sub directory. ( this is with 0.38.10)

![image](https://user-images.githubusercontent.com/8997401/219788296-850446b2-0549-4b3e-bc5e-426552ef0cab.png)

Adding the `./` to the include makes it work:
![image](https://user-images.githubusercontent.com/8997401/219788771-9e00209b-b2ff-44ff-b3a8-01541e07fe12.png)


Removing the `antora.yaml` also makes it work:

![image](https://user-images.githubusercontent.com/8997401/219788889-2188fa54-dd3d-4e2a-98b3-66adffc61bde.png)

**Comment by arnoan** [comment] 2023-02-17 21:37
Hi @mmoerdijk,

I stumbled across this issue by incident. But I do believe that the "issue" you describe is in fact intended behavior in an Antora context.

To my understanding, what happens is that when using the `include::` directive inside Antora to include another page resource it only considers the contents _directly_ inside the `pages` folder of the current module (unless further coordinates are specified of course). Since your example pages are both located in a sub-folder of the `pages` folder, a relative path `./include.adoc` must be used and - as you show in your example - that works as intended.

Here's the relevant section on this in the Antora documentation:
https://docs.antora.org/antora/latest/page/include-a-page/#token

A little higher up on that same documentation page I also found the following

![image](https://user-images.githubusercontent.com/12040852/219798185-2cc4450f-0759-47ce-a822-636befeed05c.png)

**Comment by arnoan** [comment] 2023-02-17 21:41
So either `include::./include.adoc[]` or `include::subdir/include.adoc[]` should work in your case. The key here is that Antora takes the `pages` directory of the current folder as the starting point for locating the intended target file. 

So using just `include::include.adoc[]` will only look directly inside the `pages` folder which doesn't contain such a file and thus the error message you see for it being unable to locate the file. (Unsolved directive..)

**Comment by ahus1** [comment] 2023-02-17 21:43
@mmoerdijk - thanks for adding more context, and @arnoan for looking up the specs. 

The AsciiDoc plugin is trying to replicate Antora's behavior once it identifies an Antora component by its `antora.yml`. 

The ultimate test would be to test what Antora does - and the Antora implementation is always right. I won't have time for that today. If someone would lend a hand here, that would be appreciated. Thanks!

**Comment by mmoerdijk** [comment] 2023-02-20 05:57
Hi we use Antora for our internal documentation.  

I can confirm that on version `3.1.1` of antora these include work.

**Comment by ahus1** [comment] 2023-03-01 17:56
Thank you for testing this, @mmoerdijk. As this works on Antora and the AsciiDoc plugin works the same way, I now close this issue.

**Comment by mmoerdijk** [comment] 2023-03-01 18:52
@ahus1 , i argue the opposite, the plugin does not work the same way. The includes from my example that do not work with the plugin work with antora

**Comment by ahus1** [comment] 2023-03-01 19:05
@mmoerdijk - thanks for clarifying, I misunderstood your comment. I now reopen the issue and I'll eventually build an example project to test this.

**Comment by ahus1** [comment] 2023-03-05 22:20
I took the time to investigate this further. From the [Antora docs](https://docs.antora.org/antora/latest/page/include-a-page/#token): 

> You may find that the include directive resolves the target page when the ./ token isn’t used in the file coordinate. However, we strongly recommend using the ./ token when referencing a target page that is stored in the same subdirectory as the current page.

As this plugin aims to work like Antora, the next version will support both variants for rendering the preview. It will also not show an error in the editor.

**Comment by ahus1** [comment] 2023-03-05 22:49
There's now pre-release 0.38.12 that includes this change. Please give it a try and let me know if it works for you as well. Thanks!

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by mmoerdijk** [comment] 2023-03-06 05:50
@ahus1 I just tested the new release of the plugin, and it now works like expected. Thank you very much. 

And thanks for the link to the Antora docs, I will start updating the links to always include the `./` prefix.

**Comment by infotexture** [comment] 2023-03-06 13:21
We ran into this problem too and are very happy to see it reported and resolved before we managed to file an issue.

Thanks to everyone involved! 🙏

**Comment by ahus1** [comment] 2023-03-06 17:07
Thank @mmoerdijk for reporting and testing, and @arnoan for providing the right link to the docs and joining the triaging. 

As this now seems to work, I'm promoting 0.38.12 to a regular release and publish it to the marketplace.

**Closed by ahus1** 2023-03-06 17:07 UTC
Labels: bug
