### ISSUE TITLE
Preview stuck at Initializing / v0.25.x

### ISSUE THREAD

**Issue by kota65535** [asciidoctor/asciidoctor-intellij-plugin#258] opened 2019-05-21 02:59 UTC
The preview window keeps showing "Initializing..." message.

AsciiDoc Plugin Version: v0.25.14
IntelliJ IDEA 2019.1.2 (Ultimate Edition)
Build #IU-191.7141.44, built on May 7, 2019
Licensed to TOMOHIKO OZAWA
Subscription is active until December 31, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ahus1** [comment] 2019-05-21 07:08
Hello @kota65535 - I'm sorry to hear the preview is not working. To investigate I ask for some more information:

* Could you please share the document you are trying to open (or a minimal part of it that breaks the preview)? 

* Sometimes the IntelliJ's "Event log" provides a hint want went wrong. Does IntelliJ show any messages there?

* The log file of IntelliJ would be helpful. You can access the log via "Help | Show Log in Explorer". 

You can send the files to me via a personal email (shown in my GitHub profile) if you don't want to post them online.

**Comment by kota65535** [comment] 2019-05-23 06:37
Sure, the document is extremely simple that only says `hello`.

Unfortunately, there is no Event log even if I repeated to open and close the view window. 

There are error logs in `idea.log` as follows:

```
2019-05-23 15:34:40,350 [265596459]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2019.1.2  Build #IU-191.7141.44 
2019-05-23 15:34:40,350 [265596459]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-05-23 15:34:40,350 [265596459]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
2019-05-23 15:34:40,351 [265596460]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: AsciiDoc version: 0.25.14 
2019-05-23 15:34:40,351 [265596460]  ERROR - plication.impl.ApplicationImpl - Last Action: ShowLog 
2019-05-23 15:34:40,939 [265597048]  ERROR - t.daemon.impl.ExternalToolPass - IdeaLoggingEvent[message=ExternalToolPass: , throwable=com.intellij.diagnostic.PluginException: annotator: org.asciidoc.intellij.annotator.ExternalAnnotator@5f440718 (class org.asciidoc.intellij.annotator.ExternalAnnotator) [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:368)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:68)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:195)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:166)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$10(BackgroundTaskUtil.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:263)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:242)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:165)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:336)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:326)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:276)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:290)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:66)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:36)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:192)
	... 32 more
Caused by: org.jruby.exceptions.MainExitException: unknown encoding name - UTF8
] 
```

**Comment by darkchoco** [comment] 2019-05-23 07:49
The same error happens in my environment. The only difference is the encoding name shown in error message - it says ms949 although I've set with UTF8 in all cases on IDE settings.
For your information this error already happened since ver.0.23 or 0.24 i.e. it's not due to the lastest upgrade.

`
java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:280)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$2.run(AsciiDocPreviewEditor.java:124)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.MainExitException: unknown encoding name - MS949`

**Comment by ahus1** [comment] 2019-05-23 19:13
@kota65535 - I see in the error message that JRuby doesn't known about UTF8. This is probably due to the missing dash "-".

Where did you enter this encoding? 

Could you please try setting it to "UTF-8" (with the dash)?

**Comment by ahus1** [comment] 2019-05-23 20:16
@darkchoco - are you running Windows as well? Could you please past the information from "Help | About" here?

**Comment by darkchoco** [comment] 2019-05-23 20:29
@ahus1 - I'm using 2 PCs with Windows 7 and 10 respectively, and the same error happens on both system.
Below is the idea.log when I open *.adoc inside IDE.

```
...
2019-05-23 22:19:59,010 [  29155]   INFO - j.ide.ui.OptionsTopHitProvider - 267 ms spent on EDT to cache options in project 
2019-05-23 22:19:59,144 [  29289]   INFO - pl.ProjectRootManagerComponent - project roots have changed 
2019-05-23 22:19:59,660 [  29805]   INFO - .diagnostic.PerformanceWatcher - Pushing properties took 127ms; general responsiveness: ok; EDT responsiveness: ok 
2019-05-23 22:19:59,862 [  30007]   INFO - .diagnostic.PerformanceWatcher - Indexable file iteration took 201ms; general responsiveness: ok; EDT responsiveness: ok 
2019-05-23 22:20:05,331 [  35476]   WARN - com.intellij.util.xmlb.Binding - no accessors for class org.jetbrains.kotlin.idea.highlighter.KotlinDefaultHighlightingSettingsProvider 
2019-05-23 22:20:05,783 [  35928]  ERROR - plication.impl.ApplicationImpl - org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated 
java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:280)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$2.run(AsciiDocPreviewEditor.java:124)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.MainExitException: unknown encoding name - MS949
2019-05-23 22:20:05,787 [  35932]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2019.1.2  Build #IU-191.7141.44 
2019-05-23 22:20:05,787 [  35932]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-05-23 22:20:05,787 [  35932]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
2019-05-23 22:20:05,795 [  35940]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: AsciiDoc version: 0.25.14 
2019-05-23 22:20:05,795 [  35940]  ERROR - plication.impl.ApplicationImpl - Last Action:  
2019-05-23 22:20:05,802 [  35947]  ERROR - plication.impl.ApplicationImpl - org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated 
java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:280)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$2.run(AsciiDocPreviewEditor.java:124)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jruby.exceptions.MainExitException: unknown encoding name - MS949
2019-05-23 22:20:05,802 [  35947]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 2019.1.2  Build #IU-191.7141.44 
2019-05-23 22:20:05,802 [  35947]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2019-05-23 22:20:05,802 [  35947]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
2019-05-23 22:20:05,803 [  35948]  ERROR - plication.impl.ApplicationImpl - Plugin to blame: AsciiDoc version: 0.25.14 
2019-05-23 22:20:05,803 [  35948]  ERROR - plication.impl.ApplicationImpl - Last Action:  
2019-05-23 22:20:06,501 [  36646]   INFO - j.ide.plugins.RepositoryHelper - using cached plugin list (updated at 2019-05-23 오후 10:19) 
2019-05-23 22:20:06,647 [  36792]  ERROR - t.daemon.impl.ExternalToolPass - IdeaLoggingEvent[message=ExternalToolPass: , throwable=com.intellij.diagnostic.PluginException: annotator: org.asciidoc.intellij.annotator.ExternalAnnotator@55f15186 (class org.asciidoc.intellij.annotator.ExternalAnnotator) [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:368)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:68)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:243)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:195)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:41)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:166)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$10(BackgroundTaskUtil.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:180)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:263)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:242)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:165)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:336)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:326)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:276)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:290)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:232)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.lambda$run$0(BoundedTaskExecutor.java:198)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:66)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.doAnnotate(ExternalAnnotator.java:36)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:192)
	... 32 more
Caused by: org.jruby.exceptions.MainExitException: unknown encoding name - MS949
] 
2019-05-23 22:20:31,481 [  61626]   INFO - rationStore.ComponentStoreImpl - Saving appFileTypeManager took 16 ms 
...
```

**Comment by kota65535** [comment] 2019-05-24 02:16
@ahus1 
I found a wrong environment variable setting `JAVA_TOOL_OPTION=-Dfile.encoding=UTF8`. After deleting that, the preview window now works like a charm. Thank you!

**Comment by ahus1** [comment] 2019-05-24 21:13
@darkchoco - if I am not mistaken MS949 is a Korean code page? 

JRuby supports only some codepages, see here for a list: https://github.com/jruby/jcodings/blob/master/src/org/jcodings/EncodingList.java

A new preview-version 0.26.8 is now available from the [GitHub releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) that will default to UTF-8 if the autodetected or configured code page is not supported by JRuby.

Please give it a try and let me know if this works for you.

Alternatively you could set an encoding in idea64.exe.vmoptions using "-Dfile.encoding=..." using any of the supported code pages.

Regards,
Alexander

**Comment by darkchoco** [comment] 2019-05-24 22:00
@ahus1 - it is Korean code page but I never use it for any config or setting in IDE - it's really odd where JRuby tries to get it.

Anyway, I downloaded the ver.0.27.8 pre-release one, installed it, and it works now. 👍 

It also works with the current latest version by adding the 'encoding' option on `idea64.exe.vmoptions` file - encoding option line doesn't exist in original vmoption file - but obviously it's not convenient.

Thank you for your efforts!

**Comment by ahus1** [comment] 2019-05-25 10:47
@darkchoco - good to hear that it now works. 

I see that JRuby support CP949, but the Wiki page I found tells me that MS949 and CP949 are not the same encoding: https://en.wikipedia.org/wiki/Unified_Hangul_Code

Do you the differences of CP949 and MS949?

Thanks,
Alexander

**Comment by darkchoco** [comment] 2019-05-25 15:40
@ahus1 - It's the same. `CP949` is the standard code page on MS Windows Korean and the extended version of `EUC-KR`. (EUC-KR is not completely supporting all Korean characters)

CP949 is also called as MS949.

The problem occurs on Java, since for some reason CP949 is treated as EUC-KR in Java world, so MS949 would be recommended instead.
Of course, UTF-8 would be better in most cases.

**Comment by ahus1** [comment] 2019-06-02 19:39
@darkchoco - thank you for the input. I did some research, but there seem to be subtle differences as one seems to be the Microsoft, the other the IBM way of things. 

As the plugin now defaults to UTF-8, I close this bug as I don't know how to improve the solution.

**Closed by ahus1** 2019-06-02 19:39 UTC
Labels: awaiting feedback

**Comment by jgriff** [comment] 2020-08-11 18:25
In case someone else stumbles up on this, I had the same issue but mine was due to numbers being declared for asciidoc attributes.

I'm using Antora, so my `antora.yml` had this:
```yaml
asciidoc:
  attributes:
    200: "200 OK"
    201: "201 Created"
    204: "204 No Content"
    400: "400 Bad Request"
    404: "404 Not Found"
    409: "409 Conflict"
```

I didn't notice it immediately, but as soon as I added those attributes to my playbook, the asciidoc preview in IDEA would also get stuck at "Initializing..." and I saw this in the Event Log:
```
Error rendering asciidoctor: Error rendering preview: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
```

The fix was to simply quote the yaml keys to turn them into strings.
```yaml
asciidoc:
  attributes:
    "200": "200 OK"
    "201": "201 Created"
    "204": "204 No Content"
    "400": "400 Bad Request"
    "404": "404 Not Found"
    "409": "409 Conflict"
```

**Comment by mojavelinux** [comment] 2020-08-11 20:29
You are correct that attribute names must be strings. I suppose the code that loads this file could coerce them.

**Comment by ahus1** [comment] 2020-08-11 22:03
@jgriff thanks for letting me know. Will make this more robust in the upcoming 0.31.20 release of the plugin.
