### ISSUE TITLE
 Error rendering asciidoctor: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor

### ISSUE THREAD

**Issue by olivier-schmitt** [asciidoctor/asciidoctor-intellij-plugin#187] opened 2017-08-26 17:27 UTC
Hello,

I got this event log :

**09:07	Error rendering asciidoctor: Error rendering asciidoctor: java.lang.IllegalStateException: Already installed
09:07	Error rendering asciidoctor: Error rendering asciidoctor: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor**

AsciiDoc Plugin Version: 

**0.19.0 Support Icon fonts (thanks to Matthias Balke) Update to asciidoctorj-1.5.6 (aka asciidoctor-1.5.6.1) and asciidoctorj-diagram-1.5.4.1 Support "search everywhere" and "goto by name" for all AsciiDoc sections Support Markdown style sections in syntax highlighting**

IDE Name and Version: 

IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 21, 2017
**JRE: 1.8.0_144-b01 amd64**
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 4.4.0-87-generic

I changed the JDK to 1.8.0_131 and it's doing fine:

IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 21, 2017
**JRE: 1.8.0_131-b11 amd64**
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Linux 4.4.0-87-generic

Anyway, thanks for the awesome plugin !

**Comment by roytmana** [comment] 2017-08-28 19:13
Same here with exactly the same versions of JDK and IDEA

**Comment by sshling** [comment] 2017-09-01 03:10
Same here with exactly the same versions of JDK and IDEA

**Comment by ahus1** [comment] 2017-09-01 18:03
Can you click on the log message to show the exception? Please post it here so I that I reproduced the problem correctly. 

It might take 2-3 week for me to find the time to look into that. I someone want to submit a patch I would be happy to accept it.

**Maybe a workaround for now:** recent IntelliJ versions ship on almost all platforms with an included 64bit OpenJDK. Even on Windows at least when you tick an option at install time. There should be no need to install and use an Oracle JDK separately.

**Comment by emillynge** [comment] 2017-09-07 19:58
Running Idea with `JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 idea.sh` did not fix the problem for me. 

There are unfortunately no logs with datails about this exception. Only the line : `Error rendering asciidoctor: Error rendering asciidoctor: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor` logged every time a change is made in the asciidoc file.

IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.2099.14, built on September 6, 2017
IntelliJ IDEA EAP User
Expiration date: October 6, 2017
JRE: 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.8.0-040800rc8-generic

**Comment by PraeluceantBoreus** [comment] 2017-09-09 09:18
Same applies to me:

IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 21, 2017
JRE: 1.8.0_144-b01 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.12.6-1-ARCH

I've also tried it with the community edition:

IntelliJ IDEA 2017.2.2
Build #IC-172.3757.52, built on August 15, 2017
JRE: 1.8.0_144-b01 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.12.6-1-ARCH

Hopefully this will be fixed as soon as possible. I need asciidoc daily.

**Comment by ahus1** [comment] 2017-09-09 09:38
As a workaround: Please don't use a self-installed JRE/JDK, but use the 64bit JDK bundled with the IntelliJ installation. The following works for me:

IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 21, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM **by JetBrains s.r.o**
Windows 7 6.1

**Comment by PraeluceantBoreus** [comment] 2017-09-09 10:55
Yeah that works for me, thank you!

For Arch users: install `intellij-idea-ultimate-edition-jre` from the AUR.

Is there a chance, that this will be fixed in future releases? It worked for me in the past without Jetbrains JDK

**Comment by ahus1** [comment] 2017-09-09 11:16
I'm able to reproduce the issue with Oracle JDK 144 only. The JetBrains JDK works find (it even seems to be a more recent version 152).

Those using Oracle JDK, please comment here why you have chosen Oracle JDK and can't use JetBrains JDK. As stated on https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under: "All the products on all the supported platforms already have JetBrains Runtime bundled and it will be used by default." Since 2017.1 even Windows uses a pre-bundled 64bit JetBrains JDK.

**Comment by ahus1** [comment] 2017-09-09 11:44
Those running a IntelliJ version downloaded from a Linux repository without a JRE included: As 2016 JetBrains ships with a JDK for Linux when you download it from their homepage. 

They state "It's recommended to use the bundled JRE (if available). In case you have any issues with the bundled version, you can switch to the latest version of Oracle JDK or OpenJDK available for your system."

Please contact the maintainers of your distributions to provide packages with a pre-packaged JRE by default to follow JetBrains' recommendation. This will avoid other users to experience this situation.

PS: A fix is under way to make it work on other JDKs as well, but JetBrains JDK will still be the recommended and supported version.

**Comment by PraeluceantBoreus** [comment] 2017-09-09 13:58
The only reason I use OpenJDK is because some of my packages need it as dependency, so it would be redundant if I use JetBrains JDK, but since asciidoc works only with Jetbrains JDK, I will use it.

It would be interesting why the asciidoc plugin has troubles with OpenJDK and Oracles JDK.

**Comment by ahus1** [comment] 2017-09-10 19:20
There's now a 0.19.1 version available as a preview in the [releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

It updates the JRuby runtime to avoid the problem. Please give it a try. I tried it with some local documents and updating the JRuby runtime didn't introduce issues for me. I would like to get some feedback from one or some of you before I publish it officially.

**Comment by PraeluceantBoreus** [comment] 2017-09-10 21:05
Thank you, I'll try it tomorrow.

**Comment by PraeluceantBoreus** [comment] 2017-09-11 06:35
Works for me with OpenJDK `8.u144-1`. The JavaFX view works too, but since JetBrains JDK works better with HiDPi Displays, I will stick to JetBrains JDK.

**Comment by ahus1** [comment] 2017-09-12 07:23
Version 0.19.1 is now available from the JetBrains plugin repository.

**Closed by ahus1** 2017-09-12 07:23 UTC

**Comment by mistermueller** [comment] 2018-02-23 13:59
I had the same error with the default boot jre and plugin version 0.19.2 and 0.20.0.
Downgrading jruby in the lib folder of the zip worked for me to see a online preview instead of "Initializing..." in the right pane: 
replace /lib/jruby-complete-9.1.8.0.jar with jruby-complete-1.7.26.jar
