### ISSUE TITLE
Integrate Computer Aid for writing Prose

### ISSUE THREAD

**Issue by fwilhe** [asciidoctor/asciidoctor-intellij-plugin#97] opened 2015-11-09 23:38 UTC
It would be nice to integrate available tools that help writing good prose. What I have in mind is [LanguageTool](https://languagetool.org/), but there might be other suitable aids.

Ideally I imagine a deep integration into the UI, for example including visual hints like intellij provides it for common programming errors and the ability to auto correct on demand.

**Comment by bodiam** [comment] 2015-11-09 23:46
Hi @fwilhe , thanks for the idea. How would this be different form the normal spell check provided by IntelliJ?

**Comment by fwilhe** [comment] 2015-11-10 06:53
LanguageTool offers more then pure spell checking, so I think there would be an additional value in having some basic prose linting.

Let's take this example from the home page:
> use this text too see an few of of the problems

There is no wrong written word, and when I paste that into a file in IDEA, it has nothing to complain about that. LT on the other hand does notice the wrong grammar.

I'm no expert in what LT can do and how it works, but since it is written in java I think it is a very natural thing to try to integrate it.

**Comment by bodiam** [comment] 2015-11-16 12:52
Clear. In that case, sounds good. You have another train ride coming up? ;-)

**Comment by fwilhe** [comment] 2015-11-16 14:13
> You have another train ride coming up? ;-)

We'll see :)

Can you assign me to this issue?

**Comment by bodiam** [comment] 2015-11-16 14:20
Actually, I first want to make you an admin. I can't. They I wanted to assign this issue to you. I can't do that either. Something is borked.

**Comment by oyren** [comment] 2019-10-26 14:05
I know the issue is very old, but I would very much appreciate an integration of LanguageTool.

 There is already a plugin called [Grazie,](https://github.com/JetBrains/intellij-plugins/tree/master/grazie) but it doesn't work for me.

**Comment by ahus1** [comment] 2019-10-26 15:21
@oyren can you describe why it doesn't work for you or what you are looking for?
Making a third party plugin work is usually easier that wiring it on our own... I don't know the plugin you mentioned.

**Comment by oyren** [comment] 2019-10-26 15:58
@ahus1 
I played around with the plugin a little more and finally I got it working inside the supported file extensions.
Grazie do not support adoc File extension. So it doesn't check the text at all, if I use something like `text.adoc`.

**Comment by ahus1** [comment] 2019-10-26 21:46
I've had a look at the Grazi plugin. I'll extend the AsciiDoc plugin so that the Grazie plugin will provide grammar checking for AsciiDoc documents. As the Grazi plugin changes its API from 2019.2 to 2019.3 the support will be experimental and will only support the very latest version of the Grazi plugin.

**Comment by ahus1** [comment] 2019-10-27 14:50
This is part of the 0.30.14 pre-release. [From this plugin's docs](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc):

> Once the user installed the [Grazi plugin](https://plugins.jetbrains.com/plugin/12175-grazie/) (to be named Grazie in 2019.3) the editor highlights possible grammar mistakes. For now text must be included in a section or a block to be checked. A minimal file would therefore contain at least a heading and some text for the text to be checked. Grazi only supports grammar checks; to get spelling support the user needs to install a dictionary as described in the previous paragraph. Grazi supports multiple languages: Once the user configured the languages in Grazi’s plugin settings, the plugin detects the language of a section automatically. It performs all checks locally with the help of libraries from https://languagetool.org/, it doesn’t submit text written in the IDE to a third party cloud service.
>
> NOTE: This feature is experimental: As Grazi is a new plugin and the API of Grazi will change in 2019.3 (now EAP), only 2019.2 is supported.

There will be edge cases. This includes passing only the relevant parts of the AsciiDoc source to Grazi for grammar checking. Please comment in this ticket with your observations and expectations. The integration to Grazi needs revision once JetBrains released 2019.3 (IDE and Grazi).

![grammar_with_grazi](https://user-images.githubusercontent.com/3957921/67636359-0c043880-f8d0-11e9-847a-9d60ab90d7b9.gif)

**Comment by ahus1** [comment] 2019-10-27 14:51
This is part of the 0.30.14 pre-release. 
It is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

[From this plugin's docs](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc):

> Once the user installed the [Grazi plugin](https://plugins.jetbrains.com/plugin/12175-grazie/) (to be named Grazie in 2019.3) the editor highlights possible grammar mistakes. For now text must be included in a section or a block to be checked. A minimal file would therefore contain at least a heading and some text for the text to be checked. Grazi only supports grammar checks; to get spelling support the user needs to install a dictionary as described in the previous paragraph. Grazi supports multiple languages: Once the user configured the languages in Grazi’s plugin settings, the plugin detects the language of a section automatically. It performs all checks locally with the help of libraries from https://languagetool.org/, it doesn’t submit text written in the IDE to a third party cloud service.
>
> NOTE: This feature is experimental: As Grazi is a new plugin and the API of Grazi will change in 2019.3 (now EAP), only 2019.2 is supported.

There will be edge cases. This includes passing only the relevant parts of the AsciiDoc source to Grazi for grammar checking. Please comment in this ticket with your observations and expectations. The integration to Grazi needs revision once JetBrains released 2019.3 (IDE and Grazi).

![grammar_with_grazi](https://user-images.githubusercontent.com/3957921/67636359-0c043880-f8d0-11e9-847a-9d60ab90d7b9.gif)

**Comment by TanVD** [comment] 2019-10-27 16:11
Hi, I am a maintainer of Grazie plugin.
Note, that Grazie actually adds its own spellchecking dictionary with IT terms and appropriate dictionaries for enabled languages (for example, if you enable German -- it will add German spellchecking dictionary). 
Let us know if you need a help with implementation of Grammar checking strategy :) Strategy will be also be backported to a release for version 2019.2.4.

**Comment by ahus1** [comment] 2019-10-27 19:53
Hi @TanVD - thanks for reaching out. 

I saw that there is a checkbox for spell checking. Looking at the code it should disable the internal spell checker, but at least with plugin version 2019.2.4 and JetBrains IDE 2019.2 this didn't work for me and I didn't find out why. Once I disabled the internal spell checker inspection manually it didn't add the wiggly green lines on unknown words. I'll update the docs accordingly.

I look forward to the Grammar checking strategies. Is the development happening in https://github.com/JetBrains/intellij-plugins/tree/master/grazie or in the https://github.com/TanVD/Grazi repository? Where would I creates issues to discuss ideas?

I noticed that the old version adds a blank to the end of the PSI text, but the new one doesn't do this any more and even removes white space at the end. Looking forward to the next release!

Another issue I crossed: The AsciiDoc text can contain "->" for arrows, and AsciiDoc will replace them automatically with the proper arrow character upon rendering. Currently Grazie complains about this (when the corresponding rule is active). I wonder if there is/will be a hook to do such replacements before passing the text to the grammar checker, or if I should filter out these violations after the check. 

I love to hear your comments!

**Comment by oyren** [comment] 2019-10-27 21:44
@ahus1 thanks for the really fast (beta) implementation, didn't expect that, unfortunately I haven't had time to try it out yet.

Seems like discussion and issues are being posted [here](https://youtrack.jetbrains.com/issues/IDEA?q=Subsystem:%20Grazi).

**Comment by TanVD** [comment] 2019-10-27 21:54
As for spellchecker -- its implementation was not the best in versions prior to 2019.3-5.3.stable. In version 2019.3-5.3.stable+ Grazie spellchecker will be enabled automatically and you don't need to do anything. In versions prior to 2019.3-5.3.stable you'll need to check the checkbox.

Development happens in https://github.com/JetBrains/intellij-plugins/tree/master/grazie since Grazie is now developed inside IntelliJ Team.  And yep, use this [YouTrack Subsystem](https://youtrack.jetbrains.com/oauth?state=%2Fissues%2FIDEA%3Fq%3DSubsystem%3A%2520Grazi) (still not renamed, but will be)

As for white spaces -- yes, it was a hack to make LanguageTool work correctly with some PsiElements. Since version 2019.3-5.3.stable we have our own fork of LanguageTool that is in a major part a re implementation of LT, and we've fixed issue right in proofreader.

As for arrows -- in GrammarCheckingStrategy it is possible to define ignored RuleGroups. You will need to add there ignored ids (you can get them by ignoring rule you need manually and then checking grazi_global.xml in IntelliJ IDEA app directory) for your specific language.

**Comment by ahus1** [comment] 2019-10-27 22:27
Great news! Can't wait for IntelliJ 2019.3 to be released and to upgrade to the latest Grazie version (as an open source space time developer I hesitate to make the development branch of the plugin depend on EAP)

**Comment by TanVD** [comment] 2019-10-27 23:05
We've also back ported our changes to version 2019.2.4 -- so once it will be released (and it should be obviously before 2019.3) Grazie also will be released for it :) So you will need to upgrade to 2019.2.4, not 2019.3

**Comment by TanVD** [comment] 2019-10-31 14:34
Version of Grazie for 2019.2.4 was released. Feel free to migrate to GrammarCheckingStrategy :)

**Comment by ahus1** [comment] 2019-10-31 18:48
Thanks for letting me know. Migration complete. It's really faster and with the latest version IntelliJ 2019.2.4 I now longer have problems integrating Grazie's spell checker.

Pre-release 0.30.16 is ready for download. 
It is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

I consider this feature now complete; feel free to comment here and/or raise problems in new issues.

**Closed by ahus1** 2019-10-31 18:48 UTC
