### ISSUE TITLE
In JavaFX preview, the font renders illegible

### ISSUE THREAD

**Issue by dinkelaker** [asciidoctor/asciidoctor-intellij-plugin#213] opened 2018-08-10 08:36 UTC
When I use Swing as preview, the preview is more or less fine.
However, the JavaFX preview the aliasing of the font is not working. It looks very pixel-ish. 
I tried to install DejaVu and Open Sans in Windows, which I after a restart also could select as the default font (in Setting / Appearance / Default font).
However, the IntelliJ font selection seems not to be used for the preview.

I looked at older issues, but they seem to be different. 
I googled, found hints about DejaVu and Open Sans, but they did not help in my case.

As a solution, I would expect that the plug-in documentation would give some details for how to select the font used in the preview. 

Alternatively, but a more costly solution, the user could inspect the selected the font in the plug-in settings, maybe change the selection there, or give a hint where to change it. 

AsciiDoc Plugin Version: 0.20.6

IDE Name and Version: 
IntelliJ IDEA 2018.2.1 (Ultimate Edition)
Build #IU-182.3911.36, built on August 6, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by Jonas1312** [comment] 2018-09-15 09:47
Same issue here

**Comment by bs-git** [comment] 2018-11-09 11:47
Same issue here, the issue appears once windows font scaling is  set to something other than 100%. The text is barely readable once font scaling is enabled. Maybe a rendering hint is missing somewhere. Is there a workaround available?

This is _exactly_ how it looks on my screen, other text in intellij renders properly.

![image](https://user-images.githubusercontent.com/15813528/48260899-7ac95700-e41d-11e8-971a-26d9a43aeb76.png)

**Comment by bs-git** [comment] 2018-11-09 11:59
Note: the tipp from issue #209 disabling sun.java2d.uiScale.enabled=false in the idea.properties seems to temporary solve this problem for me.

**Comment by ahus1** [comment] 2019-06-16 12:24
As my development machine is now running on Windows 10 as well, I was able find out how to reproduce this issue: Windows 10, factional scaling and IDE running on JetBrains Runtime 8. 

Starting form release 0.26.20 (currently work in progress) there will be a notification that the preview might be blurry.

The notification links to a Wiki page detailing what to do and workarounds. 

Besides sun.java2d.uiScale.enabled=false the issue seems to be fixed in JBR11 (that is: running the IDE on the JetBrains Runtime 11 that is based on OpenJDK 11). 

Read more about this on the Wiki page: https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Blurry-preview

**Closed by ahus1** 2019-06-16 12:24 UTC

**Comment by dinkelaker** [comment] 2019-06-17 08:27
Thanks for your support on this issue.
