### ISSUE TITLE
JetBrains Rider: AsciiDoc does not display any help if the JCEF Browser preview is just an empty panel

### ISSUE THREAD

**Issue by schittli** [asciidoctor/asciidoctor-intellij-plugin#1308] opened 2023-03-06 08:52 UTC
Hello

**thank you very much for sharing your great work!**

## Observed vs. expected behavior
In JetBrains Rider 2022.3.2, the JCEF Browser preview does not work: it just displays an empty preview panel.
- If I switch to the Swing preview, then the preview works
- If the JCEF Browser preview should work in Rider, then it would be very useful if AsciiDoc would display an error message if rendering does not work. Why not display it directly in the empty preview panel?
- If it is known that the JCEF Browser preview does not work in Rider, then a warning should be displayed in the Settings near the "Preview Browser" dropdown, so that users don't select it 😃 

## Steps to reproduce
1. Start JetBrains Rider 2022.3.2
2. Open Rider Settings » `Languages & Frameworks` » `AsciiDoc` » `Preview browser` » `JCEF Browser`
3. Open an .adoc file and display the preview panel
    » It will be empty
5. Switch the Rider settings for `Preview browser` » `SWING`
    » The preview will be rendered and displayed

## Environment

* JetBrains Rider 2022.3.2
* Plugin Version: 0.38.10

~~IntelliJ~~ Jetbrains **Rider** Details: 
```
JetBrains Rider 2022.3.2
Build #RD-223.8617.53, built on January 25, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry:
    ide.new.project.model.index.case.sensitivity=true
    ide.workspace.model.rbs.as.tree=false
    rdclient.asyncActions=false
    platform.projectModel.workspace.model.file.index=false
    indexing.enable.entity.provider.based.indexing=false
    database.show.search.tab=false
    vcs.empty.toolwindow.show=false

Non-Bundled Plugins:
    com.chylex.intellij.inspectionlens (1.1.1)
    club.nutsoft.Github3Theme (1.2.0)
    socrates.tabshifter (0.33)
    com.vermouthx.xcode-theme (1.6.1)
    lermitage.intellij.extratci (1.24.0)
    com.settler.rider.specflow (1.15.3)
    io.gitlab.zlamalp.arc-theme-idea (2.0)
    com.tobszarny.activetabhighlighter.plugin.id (1.5.1)
    MultiHighlight (3.0.0)
    com.jetbrains.rider.android (223.8617.60)
    BrowseWordAtCaret (3.0.5)
    com.obroom.plugin.smartsearch (2023.1.1)
    com.jetbrains.CyanTheme (1.3)
    de.netnexus.camelcaseplugin (3.0.12)
    com.github.catppuccin.jetbrains (2.0.9)
    Thursday (0.1.6)
    shirotelinintellij.yasukotelin.com.github (1.9.1)
    com.markskelton.one-dark-theme (5.7.4)
    com.arcticicestudio.nord.jetbrains (0.13.0)
    Key Promoter X (2022.3.1)
    com.jetbrains.grayTheme (1.3)
    dev.jan0660.TheAboveTheme (1.0.0)
    ToolWindowsActions (1.0.3)
    hunspell (223.8214.24)
    dev.lankydan.tranquil (0.0.5)
    XmlDocInspections (2.18.0.80)
    com.github.voml.neo_theme (0.3.0)
    com.clutcher.comments_highlighter (2.5.3)
    org.asciidoctor.intellij.asciidoc (0.38.10)
    org.igu.plugins.bettercomments (1.0)
    com.blai30.lotus.theme (1.10)
    com.mnw.tabmover (1.5.0)
```

Thanks a lot, kind regards,
Thomas

**Comment by schittli** [comment] 2023-03-06 09:15
- It looks like JetBrains Rider supports JCEF, because the Rider manual talks about it:
    https://www.jetbrains.com/help/rider/Invalidate_caches.html
- Unfortunately, invalidating the Rider Browser Cache does not resolve the AsciiDoc preview issue: the preview panel is still empty
- **It's very sad that AsciiDoc does not recognize that the preview panel is empty and then displays debugging information**

**Comment by schittli** [comment] 2023-03-06 09:30
**⚠️ I have found a workaround to solve the issue:**

Hello

I have read your great AsciiDoc setup & configuration manual and then thought, that uninstalling the AsciiDoc Plugin and reinstalling could help. 

After I did the following steps, the JCEF Browser preview perfectly works:
1. Uninstall the JetBrains Rider AsciiDoc Plugin 
2. Restart JetBrains Rider 
3. Reinstall the AsciiDoc Plugin 
4. As soon as you open an `.adoc` file, **the preview panel displays: "Initializing..."**
    After some seconds, the preview is rendered.

❓ What is AsciiDoc doing while it displays the "Initializing..." text in the preview Panel?

It looks like this init-process fixes the JCEF preview issue 😄 

Thanks a lot, kind regards,
Thomas

**Comment by ahus1** [comment] 2023-03-09 18:22
The some seconds "Initializing..." are expected, as it initialized JRuby for the preview. This is done only for the first AsciiDoc file that you open in your IDE during a session. It will be a lot faster from the second AsciIDoc file onwards. 

Can you still reproduce the empty preview? There have been issues before, and I'm looking for a way to reproduce it.

**Comment by ahus1** [comment] 2023-12-25 13:45
I've tested this with the latest version of Rider and I can't reproduce it. Therefore I'm closing it. 

If someone else experiences it, it might be due to using a remote desktop to access Rider: See how to [disable the GPU support as described in the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html#preview-not-showing-on-rdp-workaround-available) to prevent this.

**Closed by ahus1** 2023-12-25 13:45 UTC
Labels: bug, awaiting feedback
