### ISSUE TITLE
Bold font used on the preview where it should be regular font

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#420] opened 2020-03-12 10:17 UTC
```
= Bold

This is bold.

== Bold ?

Bold again ?
```

![bold](https://user-images.githubusercontent.com/333276/76511165-0d836700-6453-11ea-81f6-b59578150f32.png)

**AsciiDoc Plugin Version**

`0.30.41`

**IDE Name and Version**

```
WebStorm 2019.3.3
Build #WS-193.6494.34, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-88-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1931M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: BashSupport, net.seesharpsoft.intellij.plugins.csv, org.asciidoctor.intellij.asciidoc, org.jetbrains.plugins.slim, org.toml.lang
```

**Comment by ahus1** [comment] 2020-03-12 19:55
I found this happening now-and then and it seems to be an initialization problem of the JavaFX web preview. 

Once you restart your IDE this should be gone. I'm sorry to say that I haven't been able to reproduce it in a consistent manner, therefore I was unable to fix it. 

It might be a font initialization problem. Have you tried closing and re-opening the preview?

**Comment by Mogztter** [comment] 2020-03-12 20:11
> It might be a font initialization problem. Have you tried closing and re-opening the preview?

I did that but I didn't try to restart my IDE, I will check tomorrow.

**Comment by Mogztter** [comment] 2020-03-14 21:53
You were right, restarting my IDE solved this issue. 
@ahus1 Do you want to keep this issue around? Maybe someone will notice something that might help us find the root cause... 🕵

**Comment by abelsromero** [comment] 2020-07-19 20:25
I just experienced it. In my case, closing the file and reopening it was enough fix it.

**Comment by ahus1** [comment] 2020-09-26 22:19
IntelliJ is phasing out JavaFX in favor of JCEF; there is a near to nothing chance for this to be fixed in JavaFX.

This issue has only been observed on JavaFX, therefore I close this issue. Please comment if you disagree.

**Closed by ahus1** 2020-09-26 22:19 UTC
Labels: bug
