### ISSUE TITLE
OOM when indexing /quarkus/docs/src/main/asciidoc/mailer.adoc

### ISSUE THREAD

**Issue by CrazyCoder** [asciidoctor/asciidoctor-intellij-plugin#424] opened 2020-03-19 20:24 UTC
https://github.com/quarkusio/quarkus

```
2020-03-19 13:54:47,097 [ 164371]  ERROR - ij.psi.stubs.StubUpdatingIndex - Error indexing:file:///home/XXX/workspace/quarkus/docs/src/main/asciidoc/mailer.adoc 
java.lang.OutOfMemoryError: Java heap space
	at gnu.trove.TIntArrayList.ensureCapacity(TIntArrayList.java:94)
	at gnu.trove.TIntArrayList.add(TIntArrayList.java:138)
	at gnu.trove.TIntArrayList.insert(TIntArrayList.java:176)
	at com.intellij.lang.impl.MarkerProduction.addDone(MarkerProduction.java:111)
	at com.intellij.lang.impl.PsiBuilderImpl.processDone(PsiBuilderImpl.java:869)
	at com.intellij.lang.impl.PsiBuilderImpl.access$900(PsiBuilderImpl.java:49)
	at com.intellij.lang.impl.PsiBuilderImpl$StartMarker.done(PsiBuilderImpl.java:364)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.parseAttributeInBrackets(AsciiDocParserImpl.java:398)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.parseBlockMacro(AsciiDocParserImpl.java:474)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.parseBlockElement(AsciiDocParserImpl.java:620)
	at org.asciidoc.intellij.parser.AsciiDocParserImpl.parse(AsciiDocParserImpl.java:188)
	at org.asciidoc.intellij.parser.AsciiDocParser.parse(AsciiDocParser.java:20)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:81)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:189)
	at com.intellij.psi.impl.source.tree.LazyParseableElement$$Lambda$1965/0x0000000801725c40.run(Unknown Source)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:564)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:188)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:243)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getLastChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.pushChildren(DefaultStubBuilder.java:112)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.visitNode(DefaultStubBuilder.java:82)
	at com.intellij.psi.stubs.DefaultStubBuilder$StubBuildingWalkingVisitor.buildStubTree(DefaultStubBuilder.java:72)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTreeFor(DefaultStubBuilder.java:50)
	at com.intellij.psi.stubs.DefaultStubBuilder.buildStubTree(DefaultStubBuilder.java:39)
	at com.intellij.psi.stubs.StubTreeBuilder.buildStubTree(StubTreeBuilder.java:84)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.lambda$computeValue$0(StubUpdatingIndex.java:117)
	at com.intellij.psi.stubs.StubUpdatingIndex$1$$Lambda$2275/0x00000008018bbc40.compute(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:821)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:71)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:97)
	at com.intellij.psi.stubs.StubUpdatingIndex$1.computeValue(StubUpdatingIndex.java:93)
2020-03-19 13:54:47,098 [ 164372]  ERROR - ij.psi.stubs.StubUpdatingIndex - IntelliJ IDEA 2019.3.4  Build #IU-193.6911.18 
2020-03-19 13:54:47,099 [ 164373]  ERROR - ij.psi.stubs.StubUpdatingIndex - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-03-19 13:54:47,099 [ 164373]  ERROR - ij.psi.stubs.StubUpdatingIndex - OS: Linux 
2020-03-19 13:54:47,098 [ 164372]   INFO - .diagnostic.PerformanceWatcher - High memory usage (free 172 of 8125 MB) while dumping threads to /home/XXX/.IntelliJIdea2019.3/system/log/threadDumps-freeze-20200319-135428-IU-193.6911.18/threadDump-20200319-135447.txt 
2020-03-19 13:54:47,109 [ 164383]  ERROR - ij.psi.stubs.StubUpdatingIndex - Plugin to blame: AsciiDoc version: 0.30.41 
```

**Comment by ahus1** [comment] 2020-03-19 21:37
I'm sorry to hear this plugin is causing you troubles. I'm investigating a loop when parsing the document stated above. Expect a fix soon.

**Comment by ahus1** [comment] 2020-03-19 22:35
Version 0.30.41.1 is available that fixes this issue. If you use the pre-releases of this plugin, you should upgrade to 0.30.43. 

Using the example you provided I was able to verify the change. Therefore I close this ticket. 
If the issue persists, please comment and I'll re-open the ticket.

**Closed by ahus1** 2020-03-19 22:35 UTC
Labels: bug

**Comment by gastaldi** [comment] 2020-03-19 23:08
I can confirm that the issue is resolved. Thank you very much for the support @CrazyCoder and @ahus1 :+1:

**Comment by geoand** [comment] 2020-03-20 07:12
Thanks a ton folks!
