### ISSUE TITLE
The document preview overlaps the project view

### ISSUE THREAD

**Issue by BorzdeG** [asciidoctor/asciidoctor-intellij-plugin#751] opened 2021-05-07 13:29 UTC
## Steps to reproduce
1. Switch view "Project" to undock view mode
2. Open adoc file
3. Open view "Project"

<img width="339" alt="image" src="https://user-images.githubusercontent.com/2332528/117455096-82670980-af4f-11eb-9de9-a614a64003c6.png">

## Environment

Plugin version: 0.32.43

IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins: KotlinTIOBE (2.3), com.github.leomillon.uuidgenerator (4.3.2), com.github.novotnyr.jwt-intellij-plugin (0.11), com.intellij.ideolog (203.0.27.0), com.herbert.george.dart.extensions (0.0.1+3), com.intellij.bigdecimal-folding (0.9.9.8.6), com.jetbrains.embeddedProjectJdk (2.1), launch-url-from-string (1.0), woaini.liquibase.plugin (1.3-SNAPSHOT), com.intellij.nativeDebug (211.7142.13), String Manipulation (8.15.203.000.3), com.intellij.testGuiFramework (183.6156.11), com.jetbrains.ChooseRuntime (1.2), com.jetbrains.webstorm.web-assembly-plugin (1.3.211), detekt (1.16.0), dev.polek.adbwifi (1.2.2), hunspell (211.6693.44), ideanginx9 (0.1.9), jp.kitabatakep.intellij.plugins.PlantUMLStudio (2021.1.1), net.ashald.envfile (3.2.1), org.intellij.RegexpTester (1.0.8), org.intellij.plugins.hcl (0.7.10), org.jetbrains.idea.grammar (2021.1.1), org.jetbrains.plugins.hocon (2020.1.0), com.github.shiraji.findpullrequest (1.7.2), uk.co.ben-gibson.remote.repository.mapper (3.3.4), mobi.hsz.idea.gitignore (4.0.4-eap), name.kropp.intellij.makefile (211.6693.108), com.intellij.kubernetes (211.7142.13), org.apache.camel (0.7.4), ir.msdehghan.plugins.ansible (0.92), org.semonte.intellij.swagger (1.0.32), org.toml.lang (0.2.146.3826-211), ru.itbasis.plugins.intellij.hashGenerator (0.3), io.nimbly.tzatziki (5.0.3), com.intellij.plugins.webcomponents (211.6693.65), lermitage.intellij.extra.icons (1.52.0.201), Dart (211.7233), org.jetbrains.plugins.vue (211.7142.13), aws.toolkit (1.26-211), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), com.github.turansky.yfiles (1.7.1), com.gmail.blueboxware.extsee (1.0.6), kotest-plugin-intellij (1.1.36-IC-2021.1), com.jetbrains.packagesearch.intellij-plugin (1.0.1496-eap), net.lagerwey.cucumber-kotlin (2021.1.0), io.ktor.intellij.plugin (1.5.1-obsolete), pl.pszklarska.pubversionchecker (1.2.5), io.flutter (56.0.5), de.mariushoefler.flutter_enhancement_suite (1.5.0), zielu.gittoolbox (203.5.8), net.aquadc.mike.plugin (0.10), cn.yiiguxing.plugin.translate (3.1-201), izhangzhihao.rainbow.brackets (6.17), pro.bashsupport (2.0.0.211-beta7-eap), ru.adelf.idea.dotenv (2021.1), PlantUML integration (5.3.0), org.asciidoctor.intellij.asciidoc (0.32.43)
Kotlin: 211-1.5.0-release-759-IJ6693.72

**Comment by ahus1** [comment] 2021-05-10 06:28
Thanks for reporting this. I was able to reproduce the effect you see: the preview overlaps with any undocked view. 

I searched the IntelliJ Youtrack tracker and found two related issues. It seems to be rooted in the platform, all plugins that use the JCEF preview (including JetBrains's Markdown plugin) are affected: [IDEA-257702](https://youtrack.jetbrains.com/issue/IDEA-257702), [IDEA-252845](https://youtrack.jetbrains.com/issue/IDEA-252845).

I up-voted for these two issues; maybe you can do the same. 

I would hope that JetBrains picks up these tickets and solves them in the platform. If this is very annoying for you, I could dig into the IntelliJ internals to see if it is possible to hide some or all of the preview if there is a tool window that overlaps.

**Comment by ahus1** [comment] 2021-05-21 07:36
As this is an upstream issue, there is nothing I can do here fore now. Therefore I close it. Please comment/vote for the upstream issues.

If there are further questions, please comment here and I'll re-open the issue.

**Closed by ahus1** 2021-05-21 07:36 UTC
Labels: awaiting feedback, bug, upstream

**Comment by ahus1** [comment] 2021-09-13 15:47
Starting with 2021.2, the IDE supported "off screen rendering", see https://youtrack.jetbrains.com/issue/IDEA-265760 that should solve this.

**Comment by ahus1** [comment] 2021-09-13 16:27
This change is part of pre-release 0.35.1. To find out about other changes in the pre-release compared to the latest public release, please also have a look at the 0.34.x changes.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
