### ISSUE TITLE
Editing a document consumes a lot of CPU

### ISSUE THREAD

**Issue by odrotbohm** [asciidoctor/asciidoctor-intellij-plugin#908] opened 2021-11-04 21:14 UTC
## Observed vs. expected behavior

Editing a document consumes up to 200% CPU. Editing a document does consume a  more reasonable amount of CPU.

## Steps to reproduce

Create an Asciidoctor document. Start editing, move around in the document. CPU load drops completely if the focus is off IntelliJ. I see the CPU jump up to a 10-15% usage if I switch to IntelliJ and position the cursor in an Asciidoctor document. As soon as you start editing the file, it increases to 150-200%.

Thing's I've tried:
- Document size doesn't seem to influence the peak load significantly. If you start with an empy document it's still around 120%. The documents causing the 200% load were ~600 lines long.
- Enabling / disabling the preview doesn't make a difference.

I know all of that is pretty vague. Please let me know if there's anything I can do to help you any further.

## Environment

Plugin Version: 0.35.12 (but the effect was present in former versions as well)

IntelliJ Details:

IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Licensed to Spring framework / Oliver Gierke
Subscription is active until June 30, 2022.
For non-commercial open source development only.
Runtime version: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.windowSystem.autoShowProcessPopup=true, ide.images.show.chessboard=true
Non-Bundled Plugins: de.docs_as_co.intellij.plugin.diagramsnet (0.1.11), org.asciidoctor.intellij.asciidoc (0.35.12), jddd (0.8.1), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7), com.haulmont.jpab (5.7-212)
Kotlin: 212-1.5.31-release-546-IJ4638.7

**Comment by ahus1** [comment] 2021-11-04 21:58
Hi Oliver, thanks for reaching out about this bug. I'll ask some questions here to narrow it down. 

If you're working on an open source project, could you please share a link to the GitHub repo with me?

To get details what functionality triggers the CPU usage, please collect some profiling information for me: Choose the menu entry "Help | Diagnostic Tools | Start CPU Usage Profiling". Then edit a document for a minute or so, go back to the menu entry and choose "Stop CPU Usage Profiling". The IDE will create a file. Please send this file to my by email. You'll find my email address in my GitHub profile. 

Some ideas for short-term workarounds: 

* When the preview is open, the document preview will be rendered on each letter typed in the background. You mentioned that disabling the preview, and that it didn't change the behavior. 

* To show Asciidoctor warnings and editor in the editor, the document is rendered in the background when the foreground thread is idle. This can be disabled by un-checking the option "Show AsciiDoc errors and warnings in editor". Please try to disable this option to see if this changes your experience. If it does, it will be a short-term workaround; collecting the traces will hopefully reveal the cause.

I'm looking forward to some traces!

**Comment by odrotbohm** [comment] 2021-11-04 22:08
> If you're working on an open source project, could you please share a link to the GitHub repo with me?

It is a private (personal) project, but if in doubt I could share a current snapshot of that for you to diagnose if you want.

> Please send this file to my by email. You'll find my email address in my GitHub profile.

Email sent.

> Please try to disable this option to see if this changes your experience.

It unfortunately doesn't. Same CPU spike behavior as described.

**Comment by ahus1** [comment] 2021-11-05 08:17
Thanks for sending the profiling report. I found a code snippet that slowed down preparing AsciiDoc content for grammar checking. I optimized and cleaned up this piece of code. This is included in the latest pre-release of the plugin. 

Please give this pre-release of a plugin a try. If the problem persists, please send a second profiling report. Profiling one or two minutes should be sufficient.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by odrotbohm** [comment] 2021-11-05 08:58
I just sent you a new snapshot taken with the preview version of the plugin installed. Watching the activity monitor, I definitely think the changes did *something* I couldn't see the CPU spikes exceed 160% (without the profiling enabled, I get to 130% max) anymore. That general spike-on-type behavior still does exist, though.

I am not sure how far we (you) want to take this because I totally see that all of the stuff going on while typing will need some computations. I'll keep trying the preview version for a few days. It looks like can edit documents without the machine fanning all the time anymore which is a significant step ahead. So thanks for that!

**Comment by ahus1** [comment] 2021-11-05 15:12
Thanks for the second snapshot, I reviewed it. 

Most of the CPU was used to render the preview. Was the preview active while you edited the document? If not, the plugin might have rendered a preview where it shouldn't.

Besides that, I didn't find anything big to optimize

There is also "File | Power Safe Mode" that will disable all background tasks in the IDE. As it also disables lots of features, this might not be the thing you're looking for: validation and auto-complete is limited.

**Comment by ahus1** [comment] 2021-11-10 17:25
I've investigated a bit more to find out if caching could speed up the plugin and reduce CPU usage. 
These improvements are part of pre-release 0.35.13 of the plugin.

In addition I reached out to the IntelliJ team, and they'll provide further performance fixes in the platform as part of the upcoming 2021.3 releases. See https://youtrack.jetbrains.com/issue/IDEA-282252 for more information. 

As usual, the pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

It is the first time I've use the IntelliJ caching API. Please report any suspicious/strange plugin behavior you might observe in this issue.

**Comment by ahus1** [comment] 2021-11-10 17:29
(update: the changes are part of 0.35.14, updated the previous comment)

**Comment by odrotbohm** [comment] 2021-11-10 17:47
I'll give the prerelease a try ASAP.

**Comment by ahus1** [comment] 2021-11-26 07:16
I'm releasing 0.36.3 today that includes includes caching in more places; this should reduce background CPU usage for larger and nested documents further. 

I'm closing this issue for now. If you still experience problems, please comment here and I'll re-open this issue.

**Closed by ahus1** 2021-11-26 07:16 UTC
Labels: bug

**Comment by odrotbohm** [comment] 2021-11-26 09:11
Thanks for that, Alex. I'll give this a spin and report back, should I see similar spikes as before. 🙇
