### ISSUE TITLE
When using asciidoctor extensions: IndexOutOfBoundsException: Wrong line

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#311] opened 2019-08-05 11:03 UTC
An exception happened with latest IDEA and asciidoctor plugin. It happens repetitively as I write document...

```
ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: org.asciidoc.intellij.annotator.ExternalAnnotator@816a65a (class org.asciidoc.intellij.annotator.ExternalAnnotator) [Plugin: org.asciidoctor.intellij.asciidoc]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:403)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:69)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:253)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:219)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.access$600(ExternalToolPass.java:39)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$null$0(ExternalToolPass.java:183)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:936)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:53)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:180)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$11(BackgroundTaskUtil.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$3(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:185)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:264)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:243)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:178)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:324)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:314)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:264)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:278)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:233)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:368)
	at com.intellij.util.Alarm$Request.run(Alarm.java:355)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:224)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: Wrong line: 128. Available lines count: 53
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:212)
	at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:193)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:1003)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.apply(ExternalAnnotator.java:122)
	at org.asciidoc.intellij.annotator.ExternalAnnotator.apply(ExternalAnnotator.java:38)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doApply(ExternalToolPass.java:216)
	... 37 more
```

I think (according exception and number of lines in adoc file), that include macro have confused your plugin. Part of document with 53 lines includes this:

```
some document and some appendix at the end...

= List of rest entities

include::parts/_TestEntity.adoc[]
include::parts/_AnotherEntity.adoc[]
```

PS: I do not see any problem when writing document. I have set-up with rendering extension spring-restdocs (another issue I have filled a few days ago) in my project.

AsciiDoc Plugin Version: 0.28.27

IDE Name and Version:
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-25-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 8
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: DBN, Lombook Plugin, com.oliverlockwood.plugins.jenkinsfile, im.jeanfrancois.ideaplugins.ideafullscreen, manifold.ij, org.asciidoctor.intellij.asciidoc, com.intellij.lang.jsgraphql, training

**Comment by ahus1** [comment] 2019-08-05 13:46
The root cause for this is probably due to the fact that the spring-boot-rest-docs extension that is part of the distribution creates warning messages when preparing the content. I've created a PR https://github.com/spring-projects/spring-restdocs/pull/628 but this hasn't been merged yet. 

For now I suggest you copy the ruby extension from this branch https://github.com/ahus1/spring-restdocs/tree/poc_extension_intellij to avoid the warnings (and the exception in the plugin that results from this). 

I'll look into the code that the next bugfix release will not throw the exception.

**Comment by luvarqpp** [comment] 2019-08-05 14:08
Ehm, I used your fixed version and it stops. Thanks. Fixed for me, but I think problem is still present as you said.

**Comment by ahus1** [comment] 2019-08-05 19:17
This is now fixed in the master branch and will be part of 0.29.2 once it is released.

**Closed by ahus1** 2019-08-05 19:17 UTC
Labels: bug
