### ISSUE TITLE
This plugin crashes IntelliJ CE 2024.2.4 (on Fedora 41)

### ISSUE THREAD

**Issue by themr0c** [asciidoctor/asciidoctor-intellij-plugin#1729] opened 2024-11-06 15:20 UTC
On Fedora 41, IntelliJ CE 2024.2.4 installed with the JetBrains toolbox, opening an Asciidoc file crashes the IDE.

The issue does not happen with IntelliJ 2024.3.beta or 2024.2.2.

The issues happens with version 0.43.2 and 0.43.3 of the Asciidoc plugin.

**Comment by ahus1** [comment] 2024-11-06 21:17
Thank you for sharing this. We had a look at this earlier today, and the crash dump of IntelliJ didn't reveal details on the cause. Good to know it if fixed with the upcoming IntelliJ 2024.3 fixes it.

**Closed by ahus1** 2024-11-06 21:17 UTC
Labels: bug
