### ISSUE TITLE
Error displaying AsciiDoc files

### ISSUE THREAD

**Issue by thorstenkampe** [asciidoctor/asciidoctor-intellij-plugin#52] opened 2015-01-07 19:36 UTC
Latest Pycharm with latest plugin on Windows:
```
Error rendering asciidoctor: Error rendering asciidoctor: java.lang.RuntimeException: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor
NoClassDefFoundError: update failed for AnAction with ID=asciidoc.maketitle: com/intellij/openapi/actionSystem/DataKeys
```
How can I fix this issue?

**Comment by harrol** [comment] 2015-01-08 09:30
Seems like a duplicate of #51

**Closed by harrol** 2015-01-08 09:30 UTC

**Comment by thorstenkampe** [comment] 2015-01-08 10:03
The first error mentions a file not found: asciidoctor. Does the plugin need an external Asciidoctor installation?

**Comment by harrol** [comment] 2015-01-08 10:16
No external AsciiDoc(tor) installation is required. But I assumed that the error is caused by the NoClassDefFoundError on the second line.

Currently I do not have an installation of CLion or Pycharm to test with. I use IntelliJ Community 14.0.2 for development and that does not seem to have the issue.

I'll investigate this further at a later time.

**Comment by harrol** [comment] 2015-01-08 22:02
As you can read in the comments of issue #51 I can reproduce the bug on PyCharm. The class mentioned only exists in IntelliJ which we have been using up until now. The fix is easy but I have to sort out another problem out before I can create the pull request.
