### ISSUE TITLE
Issue with built-in preview feature on Idea 2021.1

### ISSUE THREAD

**Issue by aoudiamoncef** [asciidoctor/asciidoctor-intellij-plugin#721] opened 2021-04-10 16:57 UTC
## Observed vs. expected behavior
![image](https://user-images.githubusercontent.com/22281426/114278133-97bf4580-9a2e-11eb-9e1b-5c415fec7ff5.png)

1. Refresh preview tab or do nothing.
2. Add close button.

## Steps to reproduce

1. Open an .adoc file.
2. Click on built-in preview feature multiple times.
3. There is no button to close tabs individually.

## Environment

Plugin Version: 0.32.36

IntelliJ Details: IU-211.6693.111, built on April 6, 2021

Related to [IDEA-266506](https://youtrack.jetbrains.com/issue/IDEA-266506)

**Comment by ahus1** [comment] 2021-04-10 18:45
Thanks for submitting this issue here. I suppose this preview is something new in IntelliJ release 2021.1 and the AsciiDoc plugin will need to handle it properly.

I'll have a look over the next days what needs to be done.

I see that you also submitted an issue in Jetbrain's YouTrack issue tracker. Please use that issue tracker only for issued you find using the original JetBrains plugins, not for third party plugins like the AsciiDoc plugin. If I figure out that the cause for an issue in the AsciiDoc plugin can only be fixed when something is changed in the IntelliJ platform, I might open a YouTrack issue later.

**Comment by ahus1** [comment] 2021-04-12 14:07
I had a first look at this issue and found the following: 

* once the editor tab headings are enabled, there is a "x" visible to close the preview that can be used to close the preview (see below)
* if you choose not to have the tab headings enabled (like in your example), you can close the preview tabs after selecting them (for example with the mouse) and then using <kbd>Ctrl</kbd>+<kbd>F4</kbd>.

![image](https://user-images.githubusercontent.com/3957921/114406995-45a22f80-9ba8-11eb-823e-d425359f32af.png)

The same behavior occurs for example with HTML file and the standard IntelliJ editor. Therefore I assume for now that this is an IntelliJ UX issue.  I'll update the issue you created in YouTrack. Let's see how this evolves and if there are any follow-up action for the plugin - I might close this issue later as not related to this plugin.

**Comment by aoudiamoncef** [comment] 2021-04-12 16:35
If you have tabs disabled in your IntelliJ IDEA, you got:
![image](https://user-images.githubusercontent.com/22281426/114429528-c586c480-9bbd-11eb-8a5e-ca03a531eaed.png)

**Comment by ahus1** [comment] 2021-04-13 08:23
I see that upstream marked the issue as "fixed" without further comments. Currently I don't see anything else I could do here.

I suppose you could try to live with it "as is", wait if something changes in an upcoming 2021.2 release, or raise a new issue describing how this happens without referencing a 3rd party plugin like the AsciiDoc plugin. You could take the standard HTML view as an example.

**Closed by ahus1** 2021-04-13 08:23 UTC
Labels: awaiting feedback, upstream

**Comment by aoudiamoncef** [comment] 2021-04-13 09:24
Great news, thanks @ahus1
