### ISSUE TITLE
include not found in .adoc file 

### ISSUE THREAD

**Issue by eldor9797** [asciidoctor/asciidoctor-intellij-plugin#1479] opened 2023-11-30 07:31 UTC
AsciiDoc  0.40.7 
Windows 10
IntelliJ IDEA 2023.2.5 (Community Edition)
 Java 17
 Gradle 9.0

![изображение](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/74771471/dcf89c3c-95cf-4a89-9f8d-8cba208b694b)

**Comment by eldor9797** [comment] 2023-12-01 05:44
I have multiply open projects if one project will working anothers does not work . when I do invalidate caches it will be work anothers dose not

**Comment by ahus1** [comment] 2023-12-14 16:14
No example project has been provided, so I'm unable to reproduce this. Closing this issue. If you have more context / an example project, please comment and I'll reopen the issue.

**Closed by ahus1** 2023-12-14 16:14 UTC
Labels: bug, awaiting feedback
